# NLP Lab 5: Text Representation using Statistical and Vector Space Models
CSET346 | Q1 to Q4

In [1]:
import re, math
import numpy as np
import pandas as pd
import nltk
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from gensim.models import Word2Vec
for r in ["punkt", "punkt_tab", "stopwords"]:
    nltk.download(r, quiet=True)
pd.set_option("display.width", 250)
pd.set_option("display.max_columns", 50)
STOP = set(stopwords.words("english"))

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]", " ", text)
    return [t for t in word_tokenize(text) if t not in STOP and len(t) > 1]

## Q1. Term Frequency and TF-IDF from Scratch
**Formulas**
- TF(t, d) = count(t, d) / total terms in d
- IDF(t) = log10(N / df(t))
- TF-IDF(t, d) = TF(t, d) x IDF(t)

In [2]:
corpus1 = [
    "Machine learning is a branch of artificial intelligence. It lets computers learn from data. Machine learning models improve with more data.",
    "Deep learning uses neural networks with many layers. Neural networks learn complex patterns from large data. Deep models need powerful GPUs.",
    "Natural language processing helps computers understand human language. Text data is converted into numbers. Language models predict the next word.",
    "Cricket is a popular sport in India. The team scored many runs in the match. The bowler took five wickets and the team won.",
    "Football players train daily to improve fitness. The team won the league after a thrilling match. The striker scored many goals.",
    "Python is a popular programming language. Programmers write code to build software. Debugging code helps programmers fix errors.",
]
docs1 = ["Doc" + str(i + 1) for i in range(len(corpus1))]
proc1 = [preprocess(d) for d in corpus1]
pd.DataFrame({"Original": corpus1, "Processed": [" ".join(t) for t in proc1]}, index=docs1)

                                               Original                                          Processed
Doc1  Machine learning is a branch of artificial int...  machine learning branch artificial intelligenc...
Doc2  Deep learning uses neural networks with many l...  deep learning uses neural networks many layers...
Doc3  Natural language processing helps computers un...  natural language processing helps computers un...
Doc4  Cricket is a popular sport in India. The team ...  cricket popular sport india team scored many r...
Doc5  Football players train daily to improve fitnes...  football players train daily improve fitness t...
Doc6  Python is a popular programming language. Prog...  python popular programming language programmer...

In [3]:
for d, t in zip(docs1, proc1):
    print(d, t)

Doc1 ['machine', 'learning', 'branch', 'artificial', 'intelligence', 'lets', 'computers', 'learn', 'data', 'machine', 'learning', 'models', 'improve', 'data']
Doc2 ['deep', 'learning', 'uses', 'neural', 'networks', 'many', 'layers', 'neural', 'networks', 'learn', 'complex', 'patterns', 'large', 'data', 'deep', 'models', 'need', 'powerful', 'gpus']
Doc3 ['natural', 'language', 'processing', 'helps', 'computers', 'understand', 'human', 'language', 'text', 'data', 'converted', 'numbers', 'language', 'models', 'predict', 'next', 'word']
Doc4 ['cricket', 'popular', 'sport', 'india', 'team', 'scored', 'many', 'runs', 'match', 'bowler', 'took', 'five', 'wickets', 'team']
Doc5 ['football', 'players', 'train', 'daily', 'improve', 'fitness', 'team', 'league', 'thrilling', 'match', 'striker', 'scored', 'many', 'goals']
Doc6 ['python', 'popular', 'programming', 'language', 'programmers', 'write', 'code', 'build', 'software', 'debugging', 'code', 'helps', 'programmers', 'fix', 'errors']

In [4]:
vocab1 = sorted(set(w for t in proc1 for w in t))
print("Vocabulary size:", len(vocab1))
print(vocab1)

Vocabulary size: 66
['artificial', 'bowler', 'branch', 'build', 'code', 'complex', 'computers', 'converted', 'cricket', 'daily', 'data', 'debugging', 'deep', 'errors', 'fitness', 'five', 'fix', 'football', 'goals', 'gpus', 'helps', 'human', 'improve', 'india', 'intelligence', 'language', 'large', 'layers', 'league', 'learn', 'learning', 'lets', 'machine', 'many', 'match', 'models', 'natural', 'need', 'networks', 'neural', 'next', 'numbers', 'patterns', 'players', 'popular', 'powerful', 'predict', 'processing', 'programmers', 'programming', 'python', 'runs', 'scored', 'software', 'sport', 'striker', 'team', 'text', 'thrilling', 'took', 'train', 'understand', 'uses', 'wickets', 'word', 'write']

In [5]:
tf1 = pd.DataFrame(0.0, index=vocab1, columns=docs1)
for d, t in zip(docs1, proc1):
    c = Counter(t)
    for w in vocab1:
        tf1.loc[w, d] = c[w] / len(t)
print("TF matrix shape (vocab x docs):", tf1.shape)
tf1.round(4)

TF matrix shape (vocab x docs): (66, 6)

              Doc1    Doc2    Doc3    Doc4  Doc5    Doc6
artificial  0.0714  0.0000  0.0000  0.0000   0.0  0.0000
bowler      0.0000  0.0000  0.0000  0.0714   0.0  0.0000
branch      0.0714  0.0000  0.0000  0.0000   0.0  0.0000
build       0.0000  0.0000  0.0000  0.0000   0.0  0.0667
code        0.0000  0.0000  0.0000  0.0000   0.0  0.1333
...            ...     ...     ...     ...   ...     ...
understand  0.0000  0.0000  0.0588  0.0000   0.0  0.0000
uses        0.0000  0.0526  0.0000  0.0000   0.0  0.0000
wickets     0.0000  0.0000  0.0000  0.0714   0.0  0.0000
word        0.0000  0.0000  0.0588  0.0000   0.0  0.0000
write       0.0000  0.0000  0.0000  0.0000   0.0  0.0667

[66 rows x 6 columns]

In [6]:
N = len(proc1)
df1 = pd.Series({w: sum(w in t for t in proc1) for w in vocab1})
idf1 = np.log10(N / df1)
idf_table = pd.DataFrame({"df": df1, "IDF": idf1.round(4)})
print("IDF shape:", idf_table.shape)
idf_table

IDF shape: (66, 2)

            df     IDF
artificial   1  0.7782
bowler       1  0.7782
branch       1  0.7782
build        1  0.7782
code         1  0.7782
...         ..     ...
understand   1  0.7782
uses         1  0.7782
wickets      1  0.7782
word         1  0.7782
write        1  0.7782

[66 rows x 2 columns]

In [7]:
tfidf1 = tf1.mul(idf1, axis=0)
print("TF-IDF matrix shape (vocab x docs):", tfidf1.shape)
tfidf1.round(4)

TF-IDF matrix shape (vocab x docs): (66, 6)

              Doc1   Doc2    Doc3    Doc4  Doc5    Doc6
artificial  0.0556  0.000  0.0000  0.0000   0.0  0.0000
bowler      0.0000  0.000  0.0000  0.0556   0.0  0.0000
branch      0.0556  0.000  0.0000  0.0000   0.0  0.0000
build       0.0000  0.000  0.0000  0.0000   0.0  0.0519
code        0.0000  0.000  0.0000  0.0000   0.0  0.1038
...            ...    ...     ...     ...   ...     ...
understand  0.0000  0.000  0.0458  0.0000   0.0  0.0000
uses        0.0000  0.041  0.0000  0.0000   0.0  0.0000
wickets     0.0000  0.000  0.0000  0.0556   0.0  0.0000
word        0.0000  0.000  0.0458  0.0000   0.0  0.0000
write       0.0000  0.000  0.0000  0.0000   0.0  0.0519

[66 rows x 6 columns]

In [8]:
for d in docs1:
    top = tfidf1[d].sort_values(ascending=False).head(5)
    print(d, "->", ", ".join(f"{w} ({v:.4f})" for w, v in top.items()))

Doc1 -> machine (0.1112), learning (0.0682), lets (0.0556), artificial (0.0556), branch (0.0556)
Doc2 -> neural (0.0819), deep (0.0819), networks (0.0819), powerful (0.0410), patterns (0.0410)
Doc3 -> language (0.0842), converted (0.0458), text (0.0458), understand (0.0458), human (0.0458)
Doc4 -> team (0.0682), bowler (0.0556), sport (0.0556), cricket (0.0556), india (0.0556)
Doc5 -> football (0.0556), daily (0.0556), striker (0.0556), thrilling (0.0556), fitness (0.0556)
Doc6 -> programmers (0.1038), code (0.1038), python (0.0519), write (0.0519), errors (0.0519)

## Q2. Vector Space Model and Document Similarity

In [9]:
corpus2 = [
    "The new smartphone features a faster processor and a brighter display.",
    "The new laptop features a faster processor and a longer battery life.",
    "Researchers built an artificial intelligence system that writes software code.",
    "The cricket team won the final match by five wickets.",
    "The striker scored twice as the football team won the league match.",
    "Tennis champion won the tournament after a long and tiring final.",
    "The student council organised a workshop on programming for university students.",
    "The university announced new courses on machine learning and artificial intelligence.",
    "Tech companies invest heavily in artificial intelligence and machine learning chips.",
    "The coach praised the players after the team won the championship match.",
]
docs2 = ["D" + str(i + 1) for i in range(len(corpus2))]
proc2 = [" ".join(preprocess(d)) for d in corpus2]
pd.DataFrame({"Original": corpus2, "Processed": proc2}, index=docs2)

                                              Original                                          Processed
D1   The new smartphone features a faster processor...  new smartphone features faster processor brigh...
D2   The new laptop features a faster processor and...  new laptop features faster processor longer ba...
D3   Researchers built an artificial intelligence s...  researchers built artificial intelligence syst...
D4   The cricket team won the final match by five w...              cricket team final match five wickets
D5   The striker scored twice as the football team ...    striker scored twice football team league match
D6   Tennis champion won the tournament after a lon...       tennis champion tournament long tiring final
D7   The student council organised a workshop on pr...  student council organised workshop programming...
D8   The university announced new courses on machin...  university announced new courses machine learn...
D9   Tech companies invest heavily in artificial in...  tech companies invest heavily artificial intel...
D10  The coach praised the players after the team w...      coach praised players team championship match

In [10]:
tv = TfidfVectorizer()
X2 = tv.fit_transform(proc2)
dtm = pd.DataFrame(X2.toarray(), index=docs2, columns=tv.get_feature_names_out())
print("Document-term matrix shape (docs x terms):", dtm.shape)
dtm.round(3)

Document-term matrix shape (docs x terms): (10, 55)

,announced,artificial,battery,brighter,built,champion,championship,chips,coach,code,companies,council,courses,cricket,display,faster,features,final,five,football,heavily,intelligence,invest,laptop,league,...,match,new,organised,players,praised,processor,programming,researchers,scored,smartphone,software,striker,student,students,system,team,tech,tennis,tiring,tournament,twice,university,wickets,workshop,writes
D1,0.000,0.000,0.000,0.418,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.418,0.355,0.355,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.311,0.000,0.000,0.000,0.355,0.000,0.000,0.000,0.418,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
D2,0.000,0.000,0.386,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.328,0.328,0.000,0.000,0.000,0.000,0.000,0.000,0.386,0.000,...,0.000,0.287,0.000,0.000,0.000,0.328,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
D3,0.000,0.279,0.000,0.000,0.375,0.000,0.000,0.000,0.000,0.375,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.279,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.375,0.000,0.000,0.375,0.000,0.000,0.000,0.375,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.375
D4,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.455,0.000,0.000,0.000,0.387,0.455,0.000,0.000,0.000,0.000,0.000,0.000,...,0.338,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.338,0.000,0.000,0.000,0.000,0.000,0.000,0.455,0.000,0.000
D5,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.405,0.000,0.000,0.000,0.000,0.405,...,0.301,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.405,0.000,0.000,0.405,0.000,0.000,0.000,0.301,0.000,0.000,0.000,0.000,0.405,0.000,0.000,0.000,0.000
D6,0.000,0.000,0.000,0.000,0.000,0.418,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.355,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.418,0.418,0.418,0.000,0.000,0.000,0.000,0.000
D7,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.386,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.386,0.000,0.000,0.000,0.386,0.000,0.000,0.000,0.000,0.000,0.386,0.386,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.328,0.000,0.386,0.000
D8,0.414,0.308,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.414,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.308,0.000,0.000,0.000,...,0.000,0.308,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.352,0.000,0.000,0.000
D9,0.000,0.271,0.000,0.000,0.000,0.000,0.000,0.364,0.000,0.000,0.364,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.364,0.271,0.364,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.364,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
D10,0.000,0.000,0.000,0.000,0.000,0.000,0.443,0.000,0.443,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.329,0.000,0.000,0.443,0.443,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.329,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [11]:
for d in docs2[:3]:
    v = dtm.loc[d]
    print(d, "vector length", len(v), "| non-zero", int((v > 0).sum()))
    print(v[v > 0].round(3).to_dict(), "\n")

D1 vector length 55 | non-zero 7
{'brighter': 0.418, 'display': 0.418, 'faster': 0.355, 'features': 0.355, 'new': 0.311, 'processor': 0.355, 'smartphone': 0.418}

D2 vector length 55 | non-zero 8
{'battery': 0.386, 'faster': 0.328, 'features': 0.328, 'laptop': 0.386, 'life': 0.386, 'longer': 0.386, 'new': 0.287, 'processor': 0.328}

D3 vector length 55 | non-zero 8
{'artificial': 0.279, 'built': 0.375, 'code': 0.375, 'intelligence': 0.279, 'researchers': 0.375, 'software': 0.375, 'system': 0.375, 'writes': 0.375}

In [12]:
S2 = cosine_similarity(X2)
sim2 = pd.DataFrame(S2, index=docs2, columns=docs2)
sim2.round(3)

        D1     D2     D3     D4     D5     D6     D7     D8     D9    D10
D1   1.000  0.439  0.000  0.000  0.000  0.000  0.000  0.096  0.000  0.000
D2   0.439  1.000  0.000  0.000  0.000  0.000  0.000  0.088  0.000  0.000
D3   0.000  0.000  1.000  0.000  0.000  0.000  0.000  0.172  0.151  0.000
D4   0.000  0.000  0.000  1.000  0.204  0.137  0.000  0.000  0.000  0.223
D5   0.000  0.000  0.000  0.204  1.000  0.000  0.000  0.000  0.000  0.198
D6   0.000  0.000  0.000  0.137  0.000  1.000  0.000  0.000  0.000  0.000
D7   0.000  0.000  0.000  0.000  0.000  0.000  1.000  0.115  0.000  0.000
D8   0.096  0.088  0.172  0.000  0.000  0.000  0.115  1.000  0.385  0.000
D9   0.000  0.000  0.151  0.000  0.000  0.000  0.000  0.385  1.000  0.000
D10  0.000  0.000  0.000  0.223  0.198  0.000  0.000  0.000  0.000  1.000

In [13]:
pairs = [("D1", "D2"), ("D4", "D5"), ("D8", "D9"), ("D3", "D9"), ("D1", "D4")]
for a, b in pairs:
    print(f"cos({a}, {b}) = {sim2.loc[a, b]:.4f}")

cos(D1, D2) = 0.4388
cos(D4, D5) = 0.2037
cos(D8, D9) = 0.3846
cos(D3, D9) = 0.1510
cos(D1, D4) = 0.0000

In [14]:
upper = [(docs2[i], docs2[j], S2[i, j]) for i in range(len(docs2)) for j in range(i + 1, len(docs2))]
top_pairs = sorted(upper, key=lambda x: -x[2])[:5]
for a, b, s in top_pairs:
    print(f"{a} & {b}: {s:.4f}")
    print("  ", corpus2[int(a[1:]) - 1])
    print("  ", corpus2[int(b[1:]) - 1])

D1 & D2: 0.4388
   The new smartphone features a faster processor and a brighter display.
   The new laptop features a faster processor and a longer battery life.
D8 & D9: 0.3846
   The university announced new courses on machine learning and artificial intelligence.
   Tech companies invest heavily in artificial intelligence and machine learning chips.
D4 & D10: 0.2228
   The cricket team won the final match by five wickets.
   The coach praised the players after the team won the championship match.
D4 & D5: 0.2037
   The cricket team won the final match by five wickets.
   The striker scored twice as the football team won the league match.
D5 & D10: 0.1981
   The striker scored twice as the football team won the league match.
   The coach praised the players after the team won the championship match.

**How VSM converts text to vectors**

1. Each unique term in the corpus becomes one axis of a high-dimensional space.
2. Each document becomes a point/vector whose coordinate on an axis is the weight (count or TF-IDF) of that term in the document.
3. All documents share the same axes, so the corpus becomes a matrix of shape (documents x vocabulary).
4. Cosine similarity, cos(theta) = (A . B) / (|A| |B|), measures the angle between vectors, so length differences do not matter.

**Observation:** Pairs sharing content words (match/team/won for sports, artificial/intelligence/chips for tech) score high, while cross-topic pairs score near 0. Similarity is purely lexical: documents on the same topic with different wording score low.

## Q3. Distributional Representation and Word Vectors

In [15]:
sentences3 = [
    "the cat drinks milk", "the dog drinks water", "the cat chases the mouse", "the dog chases the cat",
    "the cat sleeps on the sofa", "the dog sleeps on the floor", "the mouse eats cheese", "the cat eats fish",
    "the dog eats meat", "the horse eats grass", "the cow drinks water", "the cow eats grass",
    "the horse runs in the field", "the dog runs in the park", "the cat runs in the garden",
    "the boy plays football in the park", "the girl plays cricket in the field", "the boy reads a book",
    "the girl reads a novel", "the teacher reads a book", "the student writes code", "the programmer writes code",
    "the student reads a book", "the programmer debugs code", "the teacher writes a book",
    "the boy drinks milk", "the girl drinks water", "the boy eats bread", "the girl eats cheese",
    "the programmer drinks coffee", "the teacher drinks coffee", "the student drinks water",
    "the boy plays cricket in the park", "the girl plays football in the garden",
    "the horse drinks water", "the cow drinks milk", "the student plays cricket", "the programmer plays football",
    "the teacher reads a novel", "the girl writes a novel",
]
print("Sentences:", len(sentences3))
tok3 = [word_tokenize(s.lower()) for s in sentences3]
print(tok3[:3])

Sentences: 40
[['the', 'cat', 'drinks', 'milk'], ['the', 'dog', 'drinks', 'water'], ['the', 'cat', 'chases', 'the', 'mouse']]

In [16]:
freq3 = Counter(w for s in tok3 for w in s)
vocab3 = sorted(freq3)
idx3 = {w: i for i, w in enumerate(vocab3)}
print("Vocabulary size:", len(vocab3))
print(freq3.most_common(15))

Vocabulary size: 41
[('the', 51), ('drinks', 10), ('eats', 7), ('in', 7), ('a', 7), ('cat', 6), ('plays', 6), ('girl', 6), ('dog', 5), ('water', 5), ('boy', 5), ('reads', 5), ('book', 4), ('teacher', 4), ('student', 4)]

In [17]:
WINDOW = 2
cooc = np.zeros((len(vocab3), len(vocab3)))
for s in tok3:
    for i, w in enumerate(s):
        for j in range(max(0, i - WINDOW), min(len(s), i + WINDOW + 1)):
            if i != j:
                cooc[idx3[w], idx3[s[j]]] += 1
cooc_df = pd.DataFrame(cooc, index=vocab3, columns=vocab3)
print("Co-occurrence matrix shape:", cooc_df.shape)
cooc_df.iloc[:12, :12].astype(int)

Co-occurrence matrix shape: (41, 41)

         a  book  boy  bread  cat  chases  cheese  code  coffee  cow  cricket  debugs
a        0     4    1      0    0       0       0     0       0    0        0       0
book     4     0    0      0    0       0       0     0       0    0        0       0
boy      1     0    0      1    0       0       0     0       0    0        1       0
bread    0     0    1      0    0       0       0     0       0    0        0       0
cat      0     0    0      0    0       2       0     0       0    0        0       0
chases   0     0    0      0    2       0       0     0       0    0        0       0
cheese   0     0    0      0    0       0       0     0       0    0        0       0
code     0     0    0      0    0       0       0     0       0    0        0       1
coffee   0     0    0      0    0       0       0     0       0    0        0       0
cow      0     0    0      0    0       0       0     0       0    0        0       0
cricket  0     0    1      0    0       0       0     0       0    0        0       0
debugs   0     0    0      0    0       0       0     1       0    0        0       0

In [18]:
selected = ["cat", "dog", "horse", "cow", "boy", "girl", "student", "programmer", "drinks", "eats", "reads", "writes", "book", "code"]
print("Selected words and frequency:", {w: freq3[w] for w in selected})
ctx_words = [w for w in vocab3 if w != "the"]
total = cooc.sum()
rs = cooc.sum(1, keepdims=True)
cs = cooc.sum(0, keepdims=True)
with np.errstate(divide="ignore", invalid="ignore"):
    pmi = np.log((cooc * total) / (rs * cs))
ppmi = np.nan_to_num(np.maximum(pmi, 0), neginf=0, posinf=0)
wv = pd.DataFrame(ppmi, index=vocab3, columns=vocab3)
sel_vecs = wv.loc[selected]
print("Selected word vectors shape:", sel_vecs.shape)
sel_vecs.round(2).iloc[:, :12]

Selected words and frequency: {'cat': 6, 'dog': 5, 'horse': 3, 'cow': 3, 'boy': 5, 'girl': 6, 'student': 4, 'programmer': 4, 'drinks': 10, 'eats': 7, 'reads': 5, 'writes': 4, 'book': 4, 'code': 3}
Selected word vectors shape: (14, 41)

               a  book   boy  bread   cat  chases  cheese  code  coffee   cow  cricket  debugs
cat         0.00  0.00  0.00   0.00  0.00    2.04    0.00  0.00    0.00  0.00     0.00    0.00
dog         0.00  0.00  0.00   0.00  0.00    1.47    0.00  0.00    0.00  0.00     0.00    0.00
horse       0.00  0.00  0.00   0.00  0.00    0.00    0.00  0.00    0.00  0.00     0.00    0.00
cow         0.00  0.00  0.00   0.00  0.00    0.00    0.00  0.00    0.00  0.00     0.00    0.00
boy         0.51  0.00  0.00   2.86  0.00    0.00    0.00  0.00    0.00  0.00     1.25    0.00
girl        1.02  0.00  0.00   0.00  0.00    0.00    1.98  0.00    0.00  0.00     1.07    0.00
student     0.73  0.00  0.00   0.00  0.00    0.00    0.00  1.98    0.00  0.00     1.47    0.00
programmer  0.00  0.00  0.00   0.00  0.00    0.00    0.00  2.68    2.39  0.00     0.00    2.68
drinks      0.00  0.00  0.15   0.00  0.03    0.00    0.00  0.00    2.17  1.36     0.00    0.00
eats        0.00  0.00  0.51   2.52  0.38    0.00    2.52  0.00    0.00  1.02     0.00    0.00
reads       1.83  2.28  0.56   0.00  0.00    0.00    0.00  0.00    0.00  0.00     0.00    0.00
writes      1.27  1.54  0.00   0.00  0.00    0.00    0.00  2.52    0.00  0.00     0.00    0.00
book        2.52  0.00  0.00   0.00  0.00    0.00    0.00  0.00    0.00  0.00     0.00    0.00
code        0.00  0.00  0.00   0.00  0.00    0.00    0.00  0.00    0.00  0.00     0.00    3.37

In [19]:
ws = pd.DataFrame(cosine_similarity(sel_vecs.values), index=selected, columns=selected)
ws.round(2)

             cat   dog  horse   cow   boy  girl  student  programmer  drinks  eats  reads  writes  book  code
cat         1.00  0.46   0.13  0.23  0.19  0.03     0.02        0.01    0.21  0.27   0.01    0.01  0.00  0.00
dog         0.46  1.00   0.30  0.17  0.03  0.13     0.15        0.02    0.17  0.29   0.01    0.01  0.00  0.00
horse       0.13  0.30   1.00  0.75  0.05  0.19     0.23        0.02    0.25  0.29   0.00    0.01  0.00  0.00
cow         0.23  0.17   0.75  1.00  0.28  0.17     0.23        0.03    0.50  0.26   0.00    0.01  0.00  0.00
boy         0.19  0.03   0.05  0.28  1.00  0.37     0.27        0.14    0.24  0.30   0.06    0.04  0.17  0.00
girl        0.03  0.13   0.19  0.17  0.37  1.00     0.54        0.21    0.19  0.26   0.15    0.10  0.38  0.11
student     0.02  0.15   0.23  0.23  0.27  0.54     1.00        0.44    0.24  0.01   0.10    0.42  0.42  0.16
programmer  0.01  0.02   0.02  0.03  0.14  0.21     0.44        1.00    0.26  0.01   0.00    0.33  0.10  0.45
drinks      0.21  0.17   0.25  0.50  0.24  0.19     0.24        0.26    1.00  0.10   0.06    0.08  0.00  0.08
eats        0.27  0.29   0.29  0.26  0.30  0.26     0.01        0.01    0.10  1.00   0.02    0.01  0.00  0.00
reads       0.01  0.01   0.00  0.00  0.06  0.15     0.10        0.00    0.06  0.02   1.00    0.73  0.30  0.07
writes      0.01  0.01   0.01  0.01  0.04  0.10     0.42        0.33    0.08  0.01   0.73    1.00  0.20  0.23
book        0.00  0.00   0.00  0.00  0.17  0.38     0.42        0.10    0.00  0.00   0.30    0.20  1.00  0.19
code        0.00  0.00   0.00  0.00  0.00  0.11     0.16        0.45    0.08  0.00   0.07    0.23  0.19  1.00

In [20]:
for w in selected:
    s = ws[w].drop(w).sort_values(ascending=False).head(3)
    print(f"{w:11s} -> " + ", ".join(f"{k} ({v:.2f})" for k, v in s.items()))

cat         -> dog (0.46), eats (0.27), cow (0.23)

dog         -> cat (0.46), horse (0.30), eats (0.29)
horse       -> cow (0.75), dog (0.30), eats (0.29)
cow         -> horse (0.75), drinks (0.50), boy (0.28)
boy         -> girl (0.37), eats (0.30), cow (0.28)
girl        -> student (0.54), book (0.38), boy (0.37)
student     -> girl (0.54), programmer (0.44), book (0.42)
programmer  -> code (0.45), student (0.44), writes (0.33)
drinks      -> cow (0.50), programmer (0.26), horse (0.25)
eats        -> boy (0.30), horse (0.29), dog (0.29)
reads       -> writes (0.73), book (0.30), girl (0.15)
writes      -> reads (0.73), student (0.42), programmer (0.33)
book        -> student (0.42), girl (0.38), reads (0.30)
code        -> programmer (0.45), writes (0.23), book (0.19)

In [21]:
fn = {"the", "a", "in", "on"}
tok3_w2v = [[w for w in s if w not in fn] for s in tok3]
w2v = Word2Vec(tok3_w2v, vector_size=30, window=2, min_count=1, sg=1, negative=5, epochs=100, seed=42, workers=1)
for w in ["cat", "boy", "drinks", "book"]:
    print(f"Co-occurrence : {w:6s} ->", [k for k in ws[w].drop(w).sort_values(ascending=False).index[:3]] if w in ws else "")
    print(f"Word2Vec      : {w:6s} ->", [(k, round(v, 2)) for k, v in w2v.wv.most_similar(w, topn=3)])

Co-occurrence : cat    ->

 ['dog', 'eats', 'cow']
Word2Vec      : cat    -> [('dog', 0.46), ('drinks', 0.37), ('cow', 0.35)]
Co-occurrence : boy    -> ['girl', 'eats', 'cow']
Word2Vec      : boy    -> [('horse', 0.4), ('girl', 0.21), ('sleeps', 0.18)]
Co-occurrence : drinks -> ['cow', 'programmer', 'horse']
Word2Vec      : drinks -> [('sleeps', 0.37), ('cat', 0.37), ('milk', 0.31)]
Co-occurrence : book   -> ['student', 'girl', 'reads']
Word2Vec      : book   -> [('reads', 0.37), ('floor', 0.3), ('chases', 0.29)]

**Distributional hypothesis:** words that occur in similar contexts have similar meanings (Firth: "You shall know a word by the company it keeps").

Here `cat`, `dog`, `horse`, `cow` all appear after `the` and next to verbs like `eats`, `drinks`, `runs`, so their context vectors are close. `boy`, `girl`, `student`, `programmer` share `plays`, `reads`, `writes`. Each word is represented by its co-occurrence row (PPMI weighted), and cosine similarity of those rows reflects similarity of meaning. The optional extension uses Word2Vec trained on the same corpus (dense 30-d vectors instead of sparse count-based vectors); with a corpus this tiny, pre-trained GloVe or Word2Vec would give better quality.

## Q4. Sentence and Document-to-Vector Representation

In [22]:
sent4 = [
    "The football team won the match yesterday",
    "The cricket team won the final match",
    "Players train hard before the match",
    "The coach praised the team after the match",
    "Neural networks learn patterns from large data",
    "Machine learning models learn from training data",
    "Deep learning models need large data",
    "Programmers write code for learning models",
    "The chef cooked fresh pasta with tomato sauce",
    "The chef baked a sweet chocolate cake",
    "The restaurant serves fresh spicy food",
    "Fresh vegetables and fruits make healthy food",
]
topic4 = ["sports"] * 4 + ["ai_tech"] * 4 + ["food"] * 4
ids4 = ["S" + str(i + 1) for i in range(len(sent4))]
proc4 = [" ".join(preprocess(s)) for s in sent4]
pd.DataFrame({"Sentence": sent4, "Topic": topic4, "Processed": proc4}, index=ids4)

                                             Sentence    Topic                                    Processed
S1          The football team won the match yesterday   sports                football team match yesterday
S2               The cricket team won the final match   sports                     cricket team final match
S3                Players train hard before the match   sports                     players train hard match
S4         The coach praised the team after the match   sports                     coach praised team match
S5     Neural networks learn patterns from large data  ai_tech    neural networks learn patterns large data
S6   Machine learning models learn from training data  ai_tech  machine learning models learn training data
S7               Deep learning models need large data  ai_tech         deep learning models need large data
S8         Programmers write code for learning models  ai_tech       programmers write code learning models
S9      The chef cooked fresh pasta with tomato sauce     food         chef cooked fresh pasta tomato sauce
S10             The chef baked a sweet chocolate cake     food              chef baked sweet chocolate cake
S11            The restaurant serves fresh spicy food     food           restaurant serves fresh spicy food
S12     Fresh vegetables and fruits make healthy food     food    fresh vegetables fruits make healthy food

In [23]:
tv4 = TfidfVectorizer()
T4 = tv4.fit_transform(proc4)
tfidf_sent = pd.DataFrame(T4.toarray(), index=ids4, columns=tv4.get_feature_names_out())
print("TF-IDF sentence matrix shape:", tfidf_sent.shape)
tfidf_sent.iloc[:5, :12].round(3)

TF-IDF sentence matrix shape:

 (12, 44)

    baked  cake  chef  chocolate  coach  code  cooked  cricket   data  deep  final  food
S1    0.0   0.0   0.0        0.0  0.000   0.0     0.0    0.000  0.000   0.0  0.000   0.0
S2    0.0   0.0   0.0        0.0  0.000   0.0     0.0    0.574  0.000   0.0  0.574   0.0
S3    0.0   0.0   0.0        0.0  0.000   0.0     0.0    0.000  0.000   0.0  0.000   0.0
S4    0.0   0.0   0.0        0.0  0.574   0.0     0.0    0.000  0.000   0.0  0.000   0.0
S5    0.0   0.0   0.0        0.0  0.000   0.0     0.0    0.000  0.338   0.0  0.000   0.0

In [24]:
tok4 = [p.split() for p in proc4]
try:
    import gensim.downloader as api
    wvec = api.load("glove-wiki-gigaword-50")
    emb_name = "pre-trained GloVe 50d"
except Exception:
    big = [preprocess(x) for x in corpus1 + corpus2 + sent4] + [[w for w in s if w not in {"the", "a", "in", "on"}] for s in tok3]
    wvec = Word2Vec(big * 20, vector_size=50, window=3, min_count=1, sg=1, epochs=30, seed=42, workers=1).wv
    emb_name = "Word2Vec trained on local corpora"
print("Embedding used:", emb_name)
def avg_vec(tokens):
    vs = [wvec[t] for t in tokens if t in wvec]
    return np.mean(vs, axis=0) if vs else np.zeros(wvec.vector_size)
A4 = np.vstack([avg_vec(t) for t in tok4])
print("Average word-vector sentence matrix shape:", A4.shape)
pd.DataFrame(A4[:3], index=ids4[:3]).round(3).iloc[:, :10]

[--------------------------------------------------] 0.0% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.0% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.0% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.0% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.0% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.0/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.1% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.1/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.2% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.3% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.2/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.4% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.3/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.5% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.6% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.4/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.7% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.5/66.0MB downloaded

[--------------------------------------------------] 0.8% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 0.9% 0.6/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.6/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.6/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.6/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.0% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.7/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.1% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.2% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.8/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.3% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 0.9/66.0MB downloaded

[--------------------------------------------------] 1.4% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.5% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.0/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.6% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.7% 1.1/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.8% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.2/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.3/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.3/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.3/66.0MB downloaded

[--------------------------------------------------] 1.9% 1.3/66.0MB downloaded

[--------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[--------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[--------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[--------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[=-------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[=-------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[=-------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[=-------------------------------------------------] 2.0% 1.3/66.0MB downloaded

[=-------------------------------------------------] 2.0% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.1% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.4/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.2% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.3% 1.5/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.4% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.6/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.5% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.6% 1.7/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.7% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.8/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.8% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 2.9% 1.9/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.0% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.0/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.1% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.2% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.1/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.3% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.2/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.4% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.5% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.3/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.6% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.4/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.7% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.8% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.5/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 3.9% 2.6/66.0MB downloaded

[=-------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[=-------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[=-------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[=-------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[==------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[==------------------------------------------------] 4.0% 2.6/66.0MB downloaded

[==------------------------------------------------] 4.0% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.0% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.0% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.1% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.7/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.2% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.8/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.3% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.4% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.5% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.5% 2.9/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.5% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.0/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.6% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.7% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.1/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.8% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.2/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.3/66.0MB downloaded

[==------------------------------------------------] 4.9% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.0% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.3/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.1% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.4/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.2% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.3% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.5/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.4% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.6/66.0MB downloaded

[==------------------------------------------------] 5.5% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.6% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.7/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.7% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.8/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.8% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 5.9% 3.9/66.0MB downloaded

[==------------------------------------------------] 6.0% 3.9/66.0MB downloaded

[==------------------------------------------------] 6.0% 3.9/66.0MB downloaded

[==------------------------------------------------] 6.0% 3.9/66.0MB downloaded

[==------------------------------------------------] 6.0% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.0% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.0% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.0% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.0% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.0/66.0MB downloaded

[===-----------------------------------------------] 6.1% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.2% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.1/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.3% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.4% 4.2/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.5% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.3/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.6% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.4/66.0MB downloaded

[===-----------------------------------------------] 6.7% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.8% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.5/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.6/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.6/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.6/66.0MB downloaded

[===-----------------------------------------------] 6.9% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.0% 4.6/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.1% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.7/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.2% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.3% 4.8/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.4% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.5% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.5% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.5% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.5% 4.9/66.0MB downloaded

[===-----------------------------------------------] 7.5% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.5% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.5% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.5% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.6% 5.0/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.7% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.1/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.8% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 7.9% 5.2/66.0MB downloaded

[===-----------------------------------------------] 8.0% 5.2/66.0MB downloaded

[===-----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[===-----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[===-----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.0% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.3/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.1% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.2% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.4/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.3% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.5/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.4% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.5% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.6/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.6% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.7/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.7% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.8% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.8/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 8.9% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 5.9/66.0MB downloaded

[====----------------------------------------------] 9.0% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.0% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.0% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.1% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.0/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.2% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.1/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.3% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.4% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.2/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.5% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.3/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.6% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.7% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.4/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.8% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.5/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.6/66.0MB downloaded

[====----------------------------------------------] 9.9% 6.6/66.0MB downloaded

[====----------------------------------------------] 10.0% 6.6/66.0MB downloaded

[====----------------------------------------------] 10.0% 6.6/66.0MB downloaded

[====----------------------------------------------] 10.0% 6.6/66.0MB downloaded

[====----------------------------------------------] 10.0% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.0% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.0% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.0% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.0% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.6/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.1% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.7/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.2% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.3% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.8/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.4% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 6.9/66.0MB downloaded

[=====---------------------------------------------] 10.5% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.6% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.0/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.7% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.1/66.0MB downloaded

[=====---------------------------------------------] 10.8% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 10.9% 7.2/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.2/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.2/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.2/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.2/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.0% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.3/66.0MB downloaded

[=====---------------------------------------------] 11.1% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.2% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.4/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.3% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.4% 7.5/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.5% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.6/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.6% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.7/66.0MB downloaded

[=====---------------------------------------------] 11.7% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.8% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.8/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.9/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.9/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.9/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.9/66.0MB downloaded

[=====---------------------------------------------] 11.9% 7.9/66.0MB downloaded

[=====---------------------------------------------] 12.0% 7.9/66.0MB downloaded

[=====---------------------------------------------] 12.0% 7.9/66.0MB downloaded

[=====---------------------------------------------] 12.0% 7.9/66.0MB downloaded

[=====---------------------------------------------] 12.0% 7.9/66.0MB downloaded

[======--------------------------------------------] 12.0% 7.9/66.0MB downloaded

[======--------------------------------------------] 12.0% 7.9/66.0MB downloaded

[======--------------------------------------------] 12.0% 7.9/66.0MB downloaded

[======--------------------------------------------] 12.0% 7.9/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.1% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.0/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.2% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.3% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.1/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.4% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.2/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.5% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.6% 8.3/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.7% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.4/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.8% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 12.9% 8.5/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.5/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.0% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.6/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.1% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.2% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.7/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.3% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.8/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.4% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.5% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.6% 8.9/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.6% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.0/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.7% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.8% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.1/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 13.9% 9.2/66.0MB downloaded

[======--------------------------------------------] 14.0% 9.2/66.0MB downloaded

[======--------------------------------------------] 14.0% 9.2/66.0MB downloaded

[======--------------------------------------------] 14.0% 9.2/66.0MB downloaded

[======--------------------------------------------] 14.0% 9.2/66.0MB downloaded

[=======-------------------------------------------] 14.0% 9.2/66.0MB downloaded

[=======-------------------------------------------] 14.0% 9.2/66.0MB downloaded

[=======-------------------------------------------] 14.0% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.0% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.1% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.3/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.2% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.4/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.3% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.4% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.5/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.5% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.6/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.6% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.7% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.7/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.8% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.8/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.9/66.0MB downloaded

[=======-------------------------------------------] 14.9% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.0% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.1% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.1% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.1% 9.9/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.1% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.0/66.0MB downloaded

[=======-------------------------------------------] 15.2% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.3% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.1/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.4% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.2/66.0MB downloaded

[=======-------------------------------------------] 15.5% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.6% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.3/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.7% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.4/66.0MB downloaded

[=======-------------------------------------------] 15.8% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 15.9% 10.5/66.0MB downloaded

[=======-------------------------------------------] 16.0% 10.5/66.0MB downloaded

[=======-------------------------------------------] 16.0% 10.5/66.0MB downloaded

[=======-------------------------------------------] 16.0% 10.5/66.0MB downloaded

[=======-------------------------------------------] 16.0% 10.5/66.0MB downloaded

[=======-------------------------------------------] 16.0% 10.6/66.0MB downloaded

[========------------------------------------------] 16.0% 10.6/66.0MB downloaded

[========------------------------------------------] 16.0% 10.6/66.0MB downloaded

[========------------------------------------------] 16.0% 10.6/66.0MB downloaded

[========------------------------------------------] 16.0% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.1% 10.6/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.2% 10.7/66.0MB downloaded

[========------------------------------------------] 16.3% 10.7/66.0MB downloaded

[========------------------------------------------] 16.3% 10.7/66.0MB downloaded

[========------------------------------------------] 16.3% 10.7/66.0MB downloaded

[========------------------------------------------] 16.3% 10.8/66.0MB downloaded

[========------------------------------------------] 16.3% 10.8/66.0MB downloaded

[========------------------------------------------] 16.3% 10.8/66.0MB downloaded

[========------------------------------------------] 16.3% 10.8/66.0MB downloaded

[========------------------------------------------] 16.3% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.8/66.0MB downloaded

[========------------------------------------------] 16.4% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.5% 10.9/66.0MB downloaded

[========------------------------------------------] 16.6% 10.9/66.0MB downloaded

[========------------------------------------------] 16.6% 10.9/66.0MB downloaded

[========------------------------------------------] 16.6% 10.9/66.0MB downloaded

[========------------------------------------------] 16.6% 10.9/66.0MB downloaded

[========------------------------------------------] 16.6% 11.0/66.0MB downloaded

[========------------------------------------------] 16.6% 11.0/66.0MB downloaded

[========------------------------------------------] 16.6% 11.0/66.0MB downloaded

[========------------------------------------------] 16.6% 11.0/66.0MB downloaded

[========------------------------------------------] 16.6% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.7% 11.0/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.8% 11.1/66.0MB downloaded

[========------------------------------------------] 16.9% 11.1/66.0MB downloaded

[========------------------------------------------] 16.9% 11.1/66.0MB downloaded

[========------------------------------------------] 16.9% 11.1/66.0MB downloaded

[========------------------------------------------] 16.9% 11.1/66.0MB downloaded

[========------------------------------------------] 16.9% 11.2/66.0MB downloaded

[========------------------------------------------] 16.9% 11.2/66.0MB downloaded

[========------------------------------------------] 16.9% 11.2/66.0MB downloaded

[========------------------------------------------] 16.9% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.0% 11.2/66.0MB downloaded

[========------------------------------------------] 17.1% 11.2/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.1% 11.3/66.0MB downloaded

[========------------------------------------------] 17.2% 11.3/66.0MB downloaded

[========------------------------------------------] 17.2% 11.3/66.0MB downloaded

[========------------------------------------------] 17.2% 11.3/66.0MB downloaded

[========------------------------------------------] 17.2% 11.3/66.0MB downloaded

[========------------------------------------------] 17.2% 11.4/66.0MB downloaded

[========------------------------------------------] 17.2% 11.4/66.0MB downloaded

[========------------------------------------------] 17.2% 11.4/66.0MB downloaded

[========------------------------------------------] 17.2% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.3% 11.4/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.4% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.5/66.0MB downloaded

[========------------------------------------------] 17.5% 11.6/66.0MB downloaded

[========------------------------------------------] 17.5% 11.6/66.0MB downloaded

[========------------------------------------------] 17.5% 11.6/66.0MB downloaded

[========------------------------------------------] 17.5% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.6% 11.6/66.0MB downloaded

[========------------------------------------------] 17.7% 11.6/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.7% 11.7/66.0MB downloaded

[========------------------------------------------] 17.8% 11.7/66.0MB downloaded

[========------------------------------------------] 17.8% 11.7/66.0MB downloaded

[========------------------------------------------] 17.8% 11.7/66.0MB downloaded

[========------------------------------------------] 17.8% 11.7/66.0MB downloaded

[========------------------------------------------] 17.8% 11.8/66.0MB downloaded

[========------------------------------------------] 17.8% 11.8/66.0MB downloaded

[========------------------------------------------] 17.8% 11.8/66.0MB downloaded

[========------------------------------------------] 17.8% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 17.9% 11.8/66.0MB downloaded

[========------------------------------------------] 18.0% 11.8/66.0MB downloaded

[========------------------------------------------] 18.0% 11.9/66.0MB downloaded

[========------------------------------------------] 18.0% 11.9/66.0MB downloaded

[========------------------------------------------] 18.0% 11.9/66.0MB downloaded

[========------------------------------------------] 18.0% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.0% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.0% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.0% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.0% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 11.9/66.0MB downloaded

[=========-----------------------------------------] 18.1% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.1% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.1% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.2% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.0/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.3% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.1/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.4% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.5% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.2/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.6% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.3/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.7% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.8% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.4/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 18.9% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.5/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.0% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.1% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.6/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.2% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.7/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.3% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.4% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.8/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.5% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 12.9/66.0MB downloaded

[=========-----------------------------------------] 19.6% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.6% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.7% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.0/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.8% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.1/66.0MB downloaded

[=========-----------------------------------------] 19.9% 13.2/66.0MB downloaded

[=========-----------------------------------------] 20.0% 13.2/66.0MB downloaded

[=========-----------------------------------------] 20.0% 13.2/66.0MB downloaded

[=========-----------------------------------------] 20.0% 13.2/66.0MB downloaded

[=========-----------------------------------------] 20.0% 13.2/66.0MB downloaded

[=========-----------------------------------------] 20.0% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.0% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.0% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.0% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.0% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.2/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.1% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.3/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.2% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.3% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.4/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.4% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.5/66.0MB downloaded

[==========----------------------------------------] 20.5% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.6% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.6/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.7% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.7/66.0MB downloaded

[==========----------------------------------------] 20.8% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 20.9% 13.8/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.8/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.8/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.8/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.0% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 13.9/66.0MB downloaded

[==========----------------------------------------] 21.1% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.2% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.0/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.3% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.4% 14.1/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.5% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.2/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.6% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.7% 14.3/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.8% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.4/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.5/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.5/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.5/66.0MB downloaded

[==========----------------------------------------] 21.9% 14.5/66.0MB downloaded

[==========----------------------------------------] 22.0% 14.5/66.0MB downloaded

[==========----------------------------------------] 22.0% 14.5/66.0MB downloaded

[==========----------------------------------------] 22.0% 14.5/66.0MB downloaded

[==========----------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.0% 14.5/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.1% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.6/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.2% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.3% 14.7/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.4% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.8/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.5% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.6% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.7% 14.9/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.7% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.0/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.8% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 22.9% 15.1/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.1/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.0% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.2/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.1% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.2% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.3/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.3% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.4/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.4% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.5% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.5/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.6% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.6/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.7% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.8% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.7/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 23.9% 15.8/66.0MB downloaded

[===========---------------------------------------] 24.0% 15.8/66.0MB downloaded

[===========---------------------------------------] 24.0% 15.8/66.0MB downloaded

[===========---------------------------------------] 24.0% 15.8/66.0MB downloaded

[===========---------------------------------------] 24.0% 15.8/66.0MB downloaded

[============--------------------------------------] 24.0% 15.8/66.0MB downloaded

[============--------------------------------------] 24.0% 15.8/66.0MB downloaded

[============--------------------------------------] 24.0% 15.9/66.0MB downloaded

[============--------------------------------------] 24.0% 15.9/66.0MB downloaded

[============--------------------------------------] 24.0% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.1% 15.9/66.0MB downloaded

[============--------------------------------------] 24.2% 15.9/66.0MB downloaded

[============--------------------------------------] 24.2% 15.9/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.2% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.0/66.0MB downloaded

[============--------------------------------------] 24.3% 16.1/66.0MB downloaded

[============--------------------------------------] 24.3% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.4% 16.1/66.0MB downloaded

[============--------------------------------------] 24.5% 16.1/66.0MB downloaded

[============--------------------------------------] 24.5% 16.1/66.0MB downloaded

[============--------------------------------------] 24.5% 16.1/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.5% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.2/66.0MB downloaded

[============--------------------------------------] 24.6% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.7% 16.3/66.0MB downloaded

[============--------------------------------------] 24.8% 16.3/66.0MB downloaded

[============--------------------------------------] 24.8% 16.3/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.8% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.4/66.0MB downloaded

[============--------------------------------------] 24.9% 16.5/66.0MB downloaded

[============--------------------------------------] 24.9% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.0% 16.5/66.0MB downloaded

[============--------------------------------------] 25.1% 16.5/66.0MB downloaded

[============--------------------------------------] 25.1% 16.5/66.0MB downloaded

[============--------------------------------------] 25.1% 16.5/66.0MB downloaded

[============--------------------------------------] 25.1% 16.6/66.0MB downloaded

[============--------------------------------------] 25.1% 16.6/66.0MB downloaded

[============--------------------------------------] 25.1% 16.6/66.0MB downloaded

[============--------------------------------------] 25.1% 16.6/66.0MB downloaded

[============--------------------------------------] 25.1% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.6/66.0MB downloaded

[============--------------------------------------] 25.2% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.3% 16.7/66.0MB downloaded

[============--------------------------------------] 25.4% 16.7/66.0MB downloaded

[============--------------------------------------] 25.4% 16.7/66.0MB downloaded

[============--------------------------------------] 25.4% 16.7/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.4% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.8/66.0MB downloaded

[============--------------------------------------] 25.5% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.6% 16.9/66.0MB downloaded

[============--------------------------------------] 25.7% 16.9/66.0MB downloaded

[============--------------------------------------] 25.7% 16.9/66.0MB downloaded

[============--------------------------------------] 25.7% 16.9/66.0MB downloaded

[============--------------------------------------] 25.7% 17.0/66.0MB downloaded

[============--------------------------------------] 25.7% 17.0/66.0MB downloaded

[============--------------------------------------] 25.7% 17.0/66.0MB downloaded

[============--------------------------------------] 25.7% 17.0/66.0MB downloaded

[============--------------------------------------] 25.7% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.0/66.0MB downloaded

[============--------------------------------------] 25.8% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 25.9% 17.1/66.0MB downloaded

[============--------------------------------------] 26.0% 17.1/66.0MB downloaded

[============--------------------------------------] 26.0% 17.1/66.0MB downloaded

[============--------------------------------------] 26.0% 17.1/66.0MB downloaded

[============--------------------------------------] 26.0% 17.1/66.0MB downloaded

[=============-------------------------------------] 26.0% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.0% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.0% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.0% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.1% 17.2/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.2% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.3/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.3% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.4% 17.4/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.5% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.5/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.6% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.7% 17.6/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.8% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.7/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.8/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.8/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.8/66.0MB downloaded

[=============-------------------------------------] 26.9% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.0% 17.8/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.1% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 17.9/66.0MB downloaded

[=============-------------------------------------] 27.2% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.2% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.2% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.2% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.3% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.0/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.4% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.1/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.5% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.6% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.2/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.7% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.3/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.8% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 27.9% 18.4/66.0MB downloaded

[=============-------------------------------------] 28.0% 18.4/66.0MB downloaded

[=============-------------------------------------] 28.0% 18.5/66.0MB downloaded

[=============-------------------------------------] 28.0% 18.5/66.0MB downloaded

[=============-------------------------------------] 28.0% 18.5/66.0MB downloaded

[==============------------------------------------] 28.0% 18.5/66.0MB downloaded

[==============------------------------------------] 28.0% 18.5/66.0MB downloaded

[==============------------------------------------] 28.0% 18.5/66.0MB downloaded

[==============------------------------------------] 28.0% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.5/66.0MB downloaded

[==============------------------------------------] 28.1% 18.6/66.0MB downloaded

[==============------------------------------------] 28.1% 18.6/66.0MB downloaded

[==============------------------------------------] 28.1% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.2% 18.6/66.0MB downloaded

[==============------------------------------------] 28.3% 18.6/66.0MB downloaded

[==============------------------------------------] 28.3% 18.6/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.3% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.7/66.0MB downloaded

[==============------------------------------------] 28.4% 18.8/66.0MB downloaded

[==============------------------------------------] 28.4% 18.8/66.0MB downloaded

[==============------------------------------------] 28.4% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.5% 18.8/66.0MB downloaded

[==============------------------------------------] 28.6% 18.8/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.6% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 18.9/66.0MB downloaded

[==============------------------------------------] 28.7% 19.0/66.0MB downloaded

[==============------------------------------------] 28.7% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.8% 19.0/66.0MB downloaded

[==============------------------------------------] 28.9% 19.0/66.0MB downloaded

[==============------------------------------------] 28.9% 19.0/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 28.9% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.1/66.0MB downloaded

[==============------------------------------------] 29.0% 19.2/66.0MB downloaded

[==============------------------------------------] 29.0% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.1% 19.2/66.0MB downloaded

[==============------------------------------------] 29.2% 19.2/66.0MB downloaded

[==============------------------------------------] 29.2% 19.2/66.0MB downloaded

[==============------------------------------------] 29.2% 19.2/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.2% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.3/66.0MB downloaded

[==============------------------------------------] 29.3% 19.4/66.0MB downloaded

[==============------------------------------------] 29.3% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.4% 19.4/66.0MB downloaded

[==============------------------------------------] 29.5% 19.4/66.0MB downloaded

[==============------------------------------------] 29.5% 19.4/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.5% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.5/66.0MB downloaded

[==============------------------------------------] 29.6% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.7% 19.6/66.0MB downloaded

[==============------------------------------------] 29.8% 19.6/66.0MB downloaded

[==============------------------------------------] 29.8% 19.6/66.0MB downloaded

[==============------------------------------------] 29.8% 19.6/66.0MB downloaded

[==============------------------------------------] 29.8% 19.7/66.0MB downloaded

[==============------------------------------------] 29.8% 19.7/66.0MB downloaded

[==============------------------------------------] 29.8% 19.7/66.0MB downloaded

[==============------------------------------------] 29.8% 19.7/66.0MB downloaded

[==============------------------------------------] 29.8% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.7/66.0MB downloaded

[==============------------------------------------] 29.9% 19.8/66.0MB downloaded

[==============------------------------------------] 29.9% 19.8/66.0MB downloaded

[==============------------------------------------] 30.0% 19.8/66.0MB downloaded

[==============------------------------------------] 30.0% 19.8/66.0MB downloaded

[==============------------------------------------] 30.0% 19.8/66.0MB downloaded

[==============------------------------------------] 30.0% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.0% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.0% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.0% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.0% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.8/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.1% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 19.9/66.0MB downloaded

[===============-----------------------------------] 30.2% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.3% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.0/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.4% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.5% 20.1/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.6% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.2/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.7% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.3/66.0MB downloaded

[===============-----------------------------------] 30.8% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 30.9% 20.4/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.4/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.4/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.4/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.4/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.0% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.1% 20.5/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.2% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.6/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.3% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.4% 20.7/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.5% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.8/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.6% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.7% 20.9/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.8% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.0/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.1/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.1/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.1/66.0MB downloaded

[===============-----------------------------------] 31.9% 21.1/66.0MB downloaded

[===============-----------------------------------] 32.0% 21.1/66.0MB downloaded

[===============-----------------------------------] 32.0% 21.1/66.0MB downloaded

[===============-----------------------------------] 32.0% 21.1/66.0MB downloaded

[===============-----------------------------------] 32.0% 21.1/66.0MB downloaded

[================----------------------------------] 32.0% 21.1/66.0MB downloaded

[================----------------------------------] 32.0% 21.1/66.0MB downloaded

[================----------------------------------] 32.0% 21.1/66.0MB downloaded

[================----------------------------------] 32.0% 21.1/66.0MB downloaded

[================----------------------------------] 32.1% 21.1/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.1% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.2/66.0MB downloaded

[================----------------------------------] 32.2% 21.3/66.0MB downloaded

[================----------------------------------] 32.2% 21.3/66.0MB downloaded

[================----------------------------------] 32.2% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.3% 21.3/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.4% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.4/66.0MB downloaded

[================----------------------------------] 32.5% 21.5/66.0MB downloaded

[================----------------------------------] 32.5% 21.5/66.0MB downloaded

[================----------------------------------] 32.5% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.6% 21.5/66.0MB downloaded

[================----------------------------------] 32.7% 21.5/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.7% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.6/66.0MB downloaded

[================----------------------------------] 32.8% 21.7/66.0MB downloaded

[================----------------------------------] 32.8% 21.7/66.0MB downloaded

[================----------------------------------] 32.8% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 32.9% 21.7/66.0MB downloaded

[================----------------------------------] 33.0% 21.7/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.0% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.8/66.0MB downloaded

[================----------------------------------] 33.1% 21.9/66.0MB downloaded

[================----------------------------------] 33.1% 21.9/66.0MB downloaded

[================----------------------------------] 33.1% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.2% 21.9/66.0MB downloaded

[================----------------------------------] 33.3% 21.9/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.3% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.0/66.0MB downloaded

[================----------------------------------] 33.4% 22.1/66.0MB downloaded

[================----------------------------------] 33.4% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.5% 22.1/66.0MB downloaded

[================----------------------------------] 33.6% 22.1/66.0MB downloaded

[================----------------------------------] 33.6% 22.1/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.6% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.2/66.0MB downloaded

[================----------------------------------] 33.7% 22.3/66.0MB downloaded

[================----------------------------------] 33.7% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.8% 22.3/66.0MB downloaded

[================----------------------------------] 33.9% 22.3/66.0MB downloaded

[================----------------------------------] 33.9% 22.3/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 33.9% 22.4/66.0MB downloaded

[================----------------------------------] 34.0% 22.4/66.0MB downloaded

[================----------------------------------] 34.0% 22.4/66.0MB downloaded

[================----------------------------------] 34.0% 22.4/66.0MB downloaded

[================----------------------------------] 34.0% 22.4/66.0MB downloaded

[=================---------------------------------] 34.0% 22.4/66.0MB downloaded

[=================---------------------------------] 34.0% 22.4/66.0MB downloaded

[=================---------------------------------] 34.0% 22.5/66.0MB downloaded

[=================---------------------------------] 34.0% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.1% 22.5/66.0MB downloaded

[=================---------------------------------] 34.2% 22.5/66.0MB downloaded

[=================---------------------------------] 34.2% 22.5/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.2% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.6/66.0MB downloaded

[=================---------------------------------] 34.3% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.4% 22.7/66.0MB downloaded

[=================---------------------------------] 34.5% 22.7/66.0MB downloaded

[=================---------------------------------] 34.5% 22.7/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.5% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.8/66.0MB downloaded

[=================---------------------------------] 34.6% 22.9/66.0MB downloaded

[=================---------------------------------] 34.6% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.7% 22.9/66.0MB downloaded

[=================---------------------------------] 34.8% 22.9/66.0MB downloaded

[=================---------------------------------] 34.8% 22.9/66.0MB downloaded

[=================---------------------------------] 34.8% 22.9/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.8% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.0/66.0MB downloaded

[=================---------------------------------] 34.9% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.0% 23.1/66.0MB downloaded

[=================---------------------------------] 35.1% 23.1/66.0MB downloaded

[=================---------------------------------] 35.1% 23.1/66.0MB downloaded

[=================---------------------------------] 35.1% 23.1/66.0MB downloaded

[=================---------------------------------] 35.1% 23.2/66.0MB downloaded

[=================---------------------------------] 35.1% 23.2/66.0MB downloaded

[=================---------------------------------] 35.1% 23.2/66.0MB downloaded

[=================---------------------------------] 35.1% 23.2/66.0MB downloaded

[=================---------------------------------] 35.1% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.2% 23.2/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.3% 23.3/66.0MB downloaded

[=================---------------------------------] 35.4% 23.3/66.0MB downloaded

[=================---------------------------------] 35.4% 23.3/66.0MB downloaded

[=================---------------------------------] 35.4% 23.3/66.0MB downloaded

[=================---------------------------------] 35.4% 23.4/66.0MB downloaded

[=================---------------------------------] 35.4% 23.4/66.0MB downloaded

[=================---------------------------------] 35.4% 23.4/66.0MB downloaded

[=================---------------------------------] 35.4% 23.4/66.0MB downloaded

[=================---------------------------------] 35.4% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.4/66.0MB downloaded

[=================---------------------------------] 35.5% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.6% 23.5/66.0MB downloaded

[=================---------------------------------] 35.7% 23.5/66.0MB downloaded

[=================---------------------------------] 35.7% 23.5/66.0MB downloaded

[=================---------------------------------] 35.7% 23.5/66.0MB downloaded

[=================---------------------------------] 35.7% 23.5/66.0MB downloaded

[=================---------------------------------] 35.7% 23.6/66.0MB downloaded

[=================---------------------------------] 35.7% 23.6/66.0MB downloaded

[=================---------------------------------] 35.7% 23.6/66.0MB downloaded

[=================---------------------------------] 35.7% 23.6/66.0MB downloaded

[=================---------------------------------] 35.7% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.8% 23.6/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 35.9% 23.7/66.0MB downloaded

[=================---------------------------------] 36.0% 23.7/66.0MB downloaded

[=================---------------------------------] 36.0% 23.7/66.0MB downloaded

[=================---------------------------------] 36.0% 23.7/66.0MB downloaded

[=================---------------------------------] 36.0% 23.8/66.0MB downloaded

[==================--------------------------------] 36.0% 23.8/66.0MB downloaded

[==================--------------------------------] 36.0% 23.8/66.0MB downloaded

[==================--------------------------------] 36.0% 23.8/66.0MB downloaded

[==================--------------------------------] 36.0% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.1% 23.8/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.2% 23.9/66.0MB downloaded

[==================--------------------------------] 36.3% 23.9/66.0MB downloaded

[==================--------------------------------] 36.3% 23.9/66.0MB downloaded

[==================--------------------------------] 36.3% 23.9/66.0MB downloaded

[==================--------------------------------] 36.3% 23.9/66.0MB downloaded

[==================--------------------------------] 36.3% 24.0/66.0MB downloaded

[==================--------------------------------] 36.3% 24.0/66.0MB downloaded

[==================--------------------------------] 36.3% 24.0/66.0MB downloaded

[==================--------------------------------] 36.3% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.4% 24.0/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.5% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.1/66.0MB downloaded

[==================--------------------------------] 36.6% 24.2/66.0MB downloaded

[==================--------------------------------] 36.6% 24.2/66.0MB downloaded

[==================--------------------------------] 36.6% 24.2/66.0MB downloaded

[==================--------------------------------] 36.6% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.7% 24.2/66.0MB downloaded

[==================--------------------------------] 36.8% 24.2/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.8% 24.3/66.0MB downloaded

[==================--------------------------------] 36.9% 24.3/66.0MB downloaded

[==================--------------------------------] 36.9% 24.3/66.0MB downloaded

[==================--------------------------------] 36.9% 24.3/66.0MB downloaded

[==================--------------------------------] 36.9% 24.3/66.0MB downloaded

[==================--------------------------------] 36.9% 24.4/66.0MB downloaded

[==================--------------------------------] 36.9% 24.4/66.0MB downloaded

[==================--------------------------------] 36.9% 24.4/66.0MB downloaded

[==================--------------------------------] 36.9% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.0% 24.4/66.0MB downloaded

[==================--------------------------------] 37.1% 24.4/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.1% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.5/66.0MB downloaded

[==================--------------------------------] 37.2% 24.6/66.0MB downloaded

[==================--------------------------------] 37.2% 24.6/66.0MB downloaded

[==================--------------------------------] 37.2% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.3% 24.6/66.0MB downloaded

[==================--------------------------------] 37.4% 24.6/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.4% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.7/66.0MB downloaded

[==================--------------------------------] 37.5% 24.8/66.0MB downloaded

[==================--------------------------------] 37.5% 24.8/66.0MB downloaded

[==================--------------------------------] 37.5% 24.8/66.0MB downloaded

[==================--------------------------------] 37.5% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.6% 24.8/66.0MB downloaded

[==================--------------------------------] 37.7% 24.8/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.7% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 24.9/66.0MB downloaded

[==================--------------------------------] 37.8% 25.0/66.0MB downloaded

[==================--------------------------------] 37.8% 25.0/66.0MB downloaded

[==================--------------------------------] 37.8% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 37.9% 25.0/66.0MB downloaded

[==================--------------------------------] 38.0% 25.0/66.0MB downloaded

[==================--------------------------------] 38.0% 25.0/66.0MB downloaded

[==================--------------------------------] 38.0% 25.1/66.0MB downloaded

[==================--------------------------------] 38.0% 25.1/66.0MB downloaded

[==================--------------------------------] 38.0% 25.1/66.0MB downloaded

[===================-------------------------------] 38.0% 25.1/66.0MB downloaded

[===================-------------------------------] 38.0% 25.1/66.0MB downloaded

[===================-------------------------------] 38.0% 25.1/66.0MB downloaded

[===================-------------------------------] 38.0% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.1/66.0MB downloaded

[===================-------------------------------] 38.1% 25.2/66.0MB downloaded

[===================-------------------------------] 38.1% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.2% 25.2/66.0MB downloaded

[===================-------------------------------] 38.3% 25.2/66.0MB downloaded

[===================-------------------------------] 38.3% 25.2/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.3% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.3/66.0MB downloaded

[===================-------------------------------] 38.4% 25.4/66.0MB downloaded

[===================-------------------------------] 38.4% 25.4/66.0MB downloaded

[===================-------------------------------] 38.4% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.5% 25.4/66.0MB downloaded

[===================-------------------------------] 38.6% 25.4/66.0MB downloaded

[===================-------------------------------] 38.6% 25.4/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.6% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.5/66.0MB downloaded

[===================-------------------------------] 38.7% 25.6/66.0MB downloaded

[===================-------------------------------] 38.7% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.8% 25.6/66.0MB downloaded

[===================-------------------------------] 38.9% 25.6/66.0MB downloaded

[===================-------------------------------] 38.9% 25.6/66.0MB downloaded

[===================-------------------------------] 38.9% 25.6/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 38.9% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.7/66.0MB downloaded

[===================-------------------------------] 39.0% 25.8/66.0MB downloaded

[===================-------------------------------] 39.0% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.1% 25.8/66.0MB downloaded

[===================-------------------------------] 39.2% 25.8/66.0MB downloaded

[===================-------------------------------] 39.2% 25.8/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.2% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 25.9/66.0MB downloaded

[===================-------------------------------] 39.3% 26.0/66.0MB downloaded

[===================-------------------------------] 39.3% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.4% 26.0/66.0MB downloaded

[===================-------------------------------] 39.5% 26.0/66.0MB downloaded

[===================-------------------------------] 39.5% 26.0/66.0MB downloaded

[===================-------------------------------] 39.5% 26.0/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.5% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.1/66.0MB downloaded

[===================-------------------------------] 39.6% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.7% 26.2/66.0MB downloaded

[===================-------------------------------] 39.8% 26.2/66.0MB downloaded

[===================-------------------------------] 39.8% 26.2/66.0MB downloaded

[===================-------------------------------] 39.8% 26.2/66.0MB downloaded

[===================-------------------------------] 39.8% 26.2/66.0MB downloaded

[===================-------------------------------] 39.8% 26.3/66.0MB downloaded

[===================-------------------------------] 39.8% 26.3/66.0MB downloaded

[===================-------------------------------] 39.8% 26.3/66.0MB downloaded

[===================-------------------------------] 39.8% 26.3/66.0MB downloaded

[===================-------------------------------] 39.8% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.3/66.0MB downloaded

[===================-------------------------------] 39.9% 26.4/66.0MB downloaded

[===================-------------------------------] 40.0% 26.4/66.0MB downloaded

[===================-------------------------------] 40.0% 26.4/66.0MB downloaded

[===================-------------------------------] 40.0% 26.4/66.0MB downloaded

[===================-------------------------------] 40.0% 26.4/66.0MB downloaded

[===================-------------------------------] 40.0% 26.4/66.0MB downloaded

[====================------------------------------] 40.0% 26.4/66.0MB downloaded

[====================------------------------------] 40.0% 26.4/66.0MB downloaded

[====================------------------------------] 40.0% 26.4/66.0MB downloaded

[====================------------------------------] 40.0% 26.4/66.0MB downloaded

[====================------------------------------] 40.1% 26.4/66.0MB downloaded

[====================------------------------------] 40.1% 26.4/66.0MB downloaded

[====================------------------------------] 40.1% 26.4/66.0MB downloaded

[====================------------------------------] 40.1% 26.5/66.0MB downloaded

[====================------------------------------] 40.1% 26.5/66.0MB downloaded

[====================------------------------------] 40.1% 26.5/66.0MB downloaded

[====================------------------------------] 40.1% 26.5/66.0MB downloaded

[====================------------------------------] 40.1% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.5/66.0MB downloaded

[====================------------------------------] 40.2% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.3% 26.6/66.0MB downloaded

[====================------------------------------] 40.4% 26.6/66.0MB downloaded

[====================------------------------------] 40.4% 26.6/66.0MB downloaded

[====================------------------------------] 40.4% 26.6/66.0MB downloaded

[====================------------------------------] 40.4% 26.6/66.0MB downloaded

[====================------------------------------] 40.4% 26.7/66.0MB downloaded

[====================------------------------------] 40.4% 26.7/66.0MB downloaded

[====================------------------------------] 40.4% 26.7/66.0MB downloaded

[====================------------------------------] 40.4% 26.7/66.0MB downloaded

[====================------------------------------] 40.4% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.7/66.0MB downloaded

[====================------------------------------] 40.5% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.6% 26.8/66.0MB downloaded

[====================------------------------------] 40.7% 26.8/66.0MB downloaded

[====================------------------------------] 40.7% 26.8/66.0MB downloaded

[====================------------------------------] 40.7% 26.8/66.0MB downloaded

[====================------------------------------] 40.7% 26.8/66.0MB downloaded

[====================------------------------------] 40.7% 26.9/66.0MB downloaded

[====================------------------------------] 40.7% 26.9/66.0MB downloaded

[====================------------------------------] 40.7% 26.9/66.0MB downloaded

[====================------------------------------] 40.7% 26.9/66.0MB downloaded

[====================------------------------------] 40.7% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.8% 26.9/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 40.9% 27.0/66.0MB downloaded

[====================------------------------------] 41.0% 27.0/66.0MB downloaded

[====================------------------------------] 41.0% 27.0/66.0MB downloaded

[====================------------------------------] 41.0% 27.0/66.0MB downloaded

[====================------------------------------] 41.0% 27.0/66.0MB downloaded

[====================------------------------------] 41.0% 27.1/66.0MB downloaded

[====================------------------------------] 41.0% 27.1/66.0MB downloaded

[====================------------------------------] 41.0% 27.1/66.0MB downloaded

[====================------------------------------] 41.0% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.1% 27.1/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.2% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.2/66.0MB downloaded

[====================------------------------------] 41.3% 27.3/66.0MB downloaded

[====================------------------------------] 41.3% 27.3/66.0MB downloaded

[====================------------------------------] 41.3% 27.3/66.0MB downloaded

[====================------------------------------] 41.3% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.4% 27.3/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.5% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.4/66.0MB downloaded

[====================------------------------------] 41.6% 27.5/66.0MB downloaded

[====================------------------------------] 41.6% 27.5/66.0MB downloaded

[====================------------------------------] 41.6% 27.5/66.0MB downloaded

[====================------------------------------] 41.6% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.7% 27.5/66.0MB downloaded

[====================------------------------------] 41.8% 27.5/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.8% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.6/66.0MB downloaded

[====================------------------------------] 41.9% 27.7/66.0MB downloaded

[====================------------------------------] 41.9% 27.7/66.0MB downloaded

[====================------------------------------] 41.9% 27.7/66.0MB downloaded

[====================------------------------------] 42.0% 27.7/66.0MB downloaded

[====================------------------------------] 42.0% 27.7/66.0MB downloaded

[====================------------------------------] 42.0% 27.7/66.0MB downloaded

[====================------------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.0% 27.7/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.1% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.8/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.2% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.3% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.4% 27.9/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.4% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.0/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.5% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.6% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.1/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.7% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.2/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.8% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 42.9% 28.3/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.3/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.0% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.4/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.1% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.2% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.5/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.3% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.6/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.4% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.5% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.7/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.6% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.8/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.7% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.8% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.9% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.9% 28.9/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 43.9% 29.0/66.0MB downloaded

[=====================-----------------------------] 44.0% 29.0/66.0MB downloaded

[=====================-----------------------------] 44.0% 29.0/66.0MB downloaded

[=====================-----------------------------] 44.0% 29.0/66.0MB downloaded

[=====================-----------------------------] 44.0% 29.0/66.0MB downloaded

[======================----------------------------] 44.0% 29.0/66.0MB downloaded

[======================----------------------------] 44.0% 29.0/66.0MB downloaded

[======================----------------------------] 44.0% 29.0/66.0MB downloaded

[======================----------------------------] 44.0% 29.1/66.0MB downloaded

[======================----------------------------] 44.0% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.1% 29.1/66.0MB downloaded

[======================----------------------------] 44.2% 29.1/66.0MB downloaded

[======================----------------------------] 44.2% 29.1/66.0MB downloaded

[======================----------------------------] 44.2% 29.1/66.0MB downloaded

[======================----------------------------] 44.2% 29.2/66.0MB downloaded

[======================----------------------------] 44.2% 29.2/66.0MB downloaded

[======================----------------------------] 44.2% 29.2/66.0MB downloaded

[======================----------------------------] 44.2% 29.2/66.0MB downloaded

[======================----------------------------] 44.2% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.2/66.0MB downloaded

[======================----------------------------] 44.3% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.4% 29.3/66.0MB downloaded

[======================----------------------------] 44.5% 29.3/66.0MB downloaded

[======================----------------------------] 44.5% 29.3/66.0MB downloaded

[======================----------------------------] 44.5% 29.3/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.5% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.4/66.0MB downloaded

[======================----------------------------] 44.6% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.7% 29.5/66.0MB downloaded

[======================----------------------------] 44.8% 29.5/66.0MB downloaded

[======================----------------------------] 44.8% 29.5/66.0MB downloaded

[======================----------------------------] 44.8% 29.5/66.0MB downloaded

[======================----------------------------] 44.8% 29.6/66.0MB downloaded

[======================----------------------------] 44.8% 29.6/66.0MB downloaded

[======================----------------------------] 44.8% 29.6/66.0MB downloaded

[======================----------------------------] 44.8% 29.6/66.0MB downloaded

[======================----------------------------] 44.8% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.6/66.0MB downloaded

[======================----------------------------] 44.9% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.0% 29.7/66.0MB downloaded

[======================----------------------------] 45.1% 29.7/66.0MB downloaded

[======================----------------------------] 45.1% 29.7/66.0MB downloaded

[======================----------------------------] 45.1% 29.7/66.0MB downloaded

[======================----------------------------] 45.1% 29.8/66.0MB downloaded

[======================----------------------------] 45.1% 29.8/66.0MB downloaded

[======================----------------------------] 45.1% 29.8/66.0MB downloaded

[======================----------------------------] 45.1% 29.8/66.0MB downloaded

[======================----------------------------] 45.1% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.8/66.0MB downloaded

[======================----------------------------] 45.2% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.3% 29.9/66.0MB downloaded

[======================----------------------------] 45.4% 29.9/66.0MB downloaded

[======================----------------------------] 45.4% 29.9/66.0MB downloaded

[======================----------------------------] 45.4% 29.9/66.0MB downloaded

[======================----------------------------] 45.4% 29.9/66.0MB downloaded

[======================----------------------------] 45.4% 30.0/66.0MB downloaded

[======================----------------------------] 45.4% 30.0/66.0MB downloaded

[======================----------------------------] 45.4% 30.0/66.0MB downloaded

[======================----------------------------] 45.4% 30.0/66.0MB downloaded

[======================----------------------------] 45.4% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.5% 30.0/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.6% 30.1/66.0MB downloaded

[======================----------------------------] 45.7% 30.1/66.0MB downloaded

[======================----------------------------] 45.7% 30.1/66.0MB downloaded

[======================----------------------------] 45.7% 30.1/66.0MB downloaded

[======================----------------------------] 45.7% 30.1/66.0MB downloaded

[======================----------------------------] 45.7% 30.2/66.0MB downloaded

[======================----------------------------] 45.7% 30.2/66.0MB downloaded

[======================----------------------------] 45.7% 30.2/66.0MB downloaded

[======================----------------------------] 45.7% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.8% 30.2/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 45.9% 30.3/66.0MB downloaded

[======================----------------------------] 46.0% 30.3/66.0MB downloaded

[======================----------------------------] 46.0% 30.3/66.0MB downloaded

[======================----------------------------] 46.0% 30.3/66.0MB downloaded

[======================----------------------------] 46.0% 30.3/66.0MB downloaded

[=======================---------------------------] 46.0% 30.4/66.0MB downloaded

[=======================---------------------------] 46.0% 30.4/66.0MB downloaded

[=======================---------------------------] 46.0% 30.4/66.0MB downloaded

[=======================---------------------------] 46.0% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.1% 30.4/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.2% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.5/66.0MB downloaded

[=======================---------------------------] 46.3% 30.6/66.0MB downloaded

[=======================---------------------------] 46.3% 30.6/66.0MB downloaded

[=======================---------------------------] 46.3% 30.6/66.0MB downloaded

[=======================---------------------------] 46.3% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.4% 30.6/66.0MB downloaded

[=======================---------------------------] 46.5% 30.6/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.5% 30.7/66.0MB downloaded

[=======================---------------------------] 46.6% 30.7/66.0MB downloaded

[=======================---------------------------] 46.6% 30.7/66.0MB downloaded

[=======================---------------------------] 46.6% 30.7/66.0MB downloaded

[=======================---------------------------] 46.6% 30.7/66.0MB downloaded

[=======================---------------------------] 46.6% 30.8/66.0MB downloaded

[=======================---------------------------] 46.6% 30.8/66.0MB downloaded

[=======================---------------------------] 46.6% 30.8/66.0MB downloaded

[=======================---------------------------] 46.6% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.7% 30.8/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.8% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 30.9/66.0MB downloaded

[=======================---------------------------] 46.9% 31.0/66.0MB downloaded

[=======================---------------------------] 46.9% 31.0/66.0MB downloaded

[=======================---------------------------] 46.9% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.0% 31.0/66.0MB downloaded

[=======================---------------------------] 47.1% 31.0/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.1% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.1/66.0MB downloaded

[=======================---------------------------] 47.2% 31.2/66.0MB downloaded

[=======================---------------------------] 47.2% 31.2/66.0MB downloaded

[=======================---------------------------] 47.2% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.3% 31.2/66.0MB downloaded

[=======================---------------------------] 47.4% 31.2/66.0MB downloaded

[=======================---------------------------] 47.4% 31.2/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.4% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.3/66.0MB downloaded

[=======================---------------------------] 47.5% 31.4/66.0MB downloaded

[=======================---------------------------] 47.5% 31.4/66.0MB downloaded

[=======================---------------------------] 47.5% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.6% 31.4/66.0MB downloaded

[=======================---------------------------] 47.7% 31.4/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.7% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.5/66.0MB downloaded

[=======================---------------------------] 47.8% 31.6/66.0MB downloaded

[=======================---------------------------] 47.8% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 47.9% 31.6/66.0MB downloaded

[=======================---------------------------] 48.0% 31.6/66.0MB downloaded

[=======================---------------------------] 48.0% 31.6/66.0MB downloaded

[=======================---------------------------] 48.0% 31.7/66.0MB downloaded

[=======================---------------------------] 48.0% 31.7/66.0MB downloaded

[========================--------------------------] 48.0% 31.7/66.0MB downloaded

[========================--------------------------] 48.0% 31.7/66.0MB downloaded

[========================--------------------------] 48.0% 31.7/66.0MB downloaded

[========================--------------------------] 48.0% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.7/66.0MB downloaded

[========================--------------------------] 48.1% 31.8/66.0MB downloaded

[========================--------------------------] 48.1% 31.8/66.0MB downloaded

[========================--------------------------] 48.1% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.2% 31.8/66.0MB downloaded

[========================--------------------------] 48.3% 31.8/66.0MB downloaded

[========================--------------------------] 48.3% 31.8/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.3% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 31.9/66.0MB downloaded

[========================--------------------------] 48.4% 32.0/66.0MB downloaded

[========================--------------------------] 48.4% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.5% 32.0/66.0MB downloaded

[========================--------------------------] 48.6% 32.0/66.0MB downloaded

[========================--------------------------] 48.6% 32.0/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.6% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.1/66.0MB downloaded

[========================--------------------------] 48.7% 32.2/66.0MB downloaded

[========================--------------------------] 48.7% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.8% 32.2/66.0MB downloaded

[========================--------------------------] 48.9% 32.2/66.0MB downloaded

[========================--------------------------] 48.9% 32.2/66.0MB downloaded

[========================--------------------------] 48.9% 32.2/66.0MB downloaded

[========================--------------------------] 48.9% 32.3/66.0MB downloaded

[========================--------------------------] 48.9% 32.3/66.0MB downloaded

[========================--------------------------] 48.9% 32.3/66.0MB downloaded

[========================--------------------------] 48.9% 32.3/66.0MB downloaded

[========================--------------------------] 48.9% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.3/66.0MB downloaded

[========================--------------------------] 49.0% 32.4/66.0MB downloaded

[========================--------------------------] 49.0% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.1% 32.4/66.0MB downloaded

[========================--------------------------] 49.2% 32.4/66.0MB downloaded

[========================--------------------------] 49.2% 32.4/66.0MB downloaded

[========================--------------------------] 49.2% 32.4/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.2% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.5/66.0MB downloaded

[========================--------------------------] 49.3% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.4% 32.6/66.0MB downloaded

[========================--------------------------] 49.5% 32.6/66.0MB downloaded

[========================--------------------------] 49.5% 32.6/66.0MB downloaded

[========================--------------------------] 49.5% 32.6/66.0MB downloaded

[========================--------------------------] 49.5% 32.7/66.0MB downloaded

[========================--------------------------] 49.5% 32.7/66.0MB downloaded

[========================--------------------------] 49.5% 32.7/66.0MB downloaded

[========================--------------------------] 49.5% 32.7/66.0MB downloaded

[========================--------------------------] 49.5% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.7/66.0MB downloaded

[========================--------------------------] 49.6% 32.8/66.0MB downloaded

[========================--------------------------] 49.6% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.7% 32.8/66.0MB downloaded

[========================--------------------------] 49.8% 32.8/66.0MB downloaded

[========================--------------------------] 49.8% 32.8/66.0MB downloaded

[========================--------------------------] 49.8% 32.8/66.0MB downloaded

[========================--------------------------] 49.8% 32.9/66.0MB downloaded

[========================--------------------------] 49.8% 32.9/66.0MB downloaded

[========================--------------------------] 49.8% 32.9/66.0MB downloaded

[========================--------------------------] 49.8% 32.9/66.0MB downloaded

[========================--------------------------] 49.8% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 32.9/66.0MB downloaded

[========================--------------------------] 49.9% 33.0/66.0MB downloaded

[========================--------------------------] 50.0% 33.0/66.0MB downloaded

[========================--------------------------] 50.0% 33.0/66.0MB downloaded

[========================--------------------------] 50.0% 33.0/66.0MB downloaded

[========================--------------------------] 50.0% 33.0/66.0MB downloaded

[=========================-------------------------] 50.0% 33.0/66.0MB downloaded

[=========================-------------------------] 50.0% 33.0/66.0MB downloaded

[=========================-------------------------] 50.0% 33.0/66.0MB downloaded

[=========================-------------------------] 50.0% 33.0/66.0MB downloaded

[=========================-------------------------] 50.1% 33.0/66.0MB downloaded

[=========================-------------------------] 50.1% 33.0/66.0MB downloaded

[=========================-------------------------] 50.1% 33.0/66.0MB downloaded

[=========================-------------------------] 50.1% 33.0/66.0MB downloaded

[=========================-------------------------] 50.1% 33.1/66.0MB downloaded

[=========================-------------------------] 50.1% 33.1/66.0MB downloaded

[=========================-------------------------] 50.1% 33.1/66.0MB downloaded

[=========================-------------------------] 50.1% 33.1/66.0MB downloaded

[=========================-------------------------] 50.1% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.2% 33.1/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.3% 33.2/66.0MB downloaded

[=========================-------------------------] 50.4% 33.2/66.0MB downloaded

[=========================-------------------------] 50.4% 33.2/66.0MB downloaded

[=========================-------------------------] 50.4% 33.2/66.0MB downloaded

[=========================-------------------------] 50.4% 33.2/66.0MB downloaded

[=========================-------------------------] 50.4% 33.3/66.0MB downloaded

[=========================-------------------------] 50.4% 33.3/66.0MB downloaded

[=========================-------------------------] 50.4% 33.3/66.0MB downloaded

[=========================-------------------------] 50.4% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.3/66.0MB downloaded

[=========================-------------------------] 50.5% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.6% 33.4/66.0MB downloaded

[=========================-------------------------] 50.7% 33.4/66.0MB downloaded

[=========================-------------------------] 50.7% 33.4/66.0MB downloaded

[=========================-------------------------] 50.7% 33.4/66.0MB downloaded

[=========================-------------------------] 50.7% 33.4/66.0MB downloaded

[=========================-------------------------] 50.7% 33.5/66.0MB downloaded

[=========================-------------------------] 50.7% 33.5/66.0MB downloaded

[=========================-------------------------] 50.7% 33.5/66.0MB downloaded

[=========================-------------------------] 50.7% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.8% 33.5/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 50.9% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.6/66.0MB downloaded

[=========================-------------------------] 51.0% 33.7/66.0MB downloaded

[=========================-------------------------] 51.0% 33.7/66.0MB downloaded

[=========================-------------------------] 51.0% 33.7/66.0MB downloaded

[=========================-------------------------] 51.0% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.1% 33.7/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.2% 33.8/66.0MB downloaded

[=========================-------------------------] 51.3% 33.8/66.0MB downloaded

[=========================-------------------------] 51.3% 33.8/66.0MB downloaded

[=========================-------------------------] 51.3% 33.8/66.0MB downloaded

[=========================-------------------------] 51.3% 33.8/66.0MB downloaded

[=========================-------------------------] 51.3% 33.9/66.0MB downloaded

[=========================-------------------------] 51.3% 33.9/66.0MB downloaded

[=========================-------------------------] 51.3% 33.9/66.0MB downloaded

[=========================-------------------------] 51.3% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.4% 33.9/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.5% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.0/66.0MB downloaded

[=========================-------------------------] 51.6% 34.1/66.0MB downloaded

[=========================-------------------------] 51.6% 34.1/66.0MB downloaded

[=========================-------------------------] 51.6% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.7% 34.1/66.0MB downloaded

[=========================-------------------------] 51.8% 34.1/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.8% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.2/66.0MB downloaded

[=========================-------------------------] 51.9% 34.3/66.0MB downloaded

[=========================-------------------------] 51.9% 34.3/66.0MB downloaded

[=========================-------------------------] 51.9% 34.3/66.0MB downloaded

[=========================-------------------------] 52.0% 34.3/66.0MB downloaded

[=========================-------------------------] 52.0% 34.3/66.0MB downloaded

[=========================-------------------------] 52.0% 34.3/66.0MB downloaded

[=========================-------------------------] 52.0% 34.3/66.0MB downloaded

[==========================------------------------] 52.0% 34.3/66.0MB downloaded

[==========================------------------------] 52.0% 34.3/66.0MB downloaded

[==========================------------------------] 52.0% 34.3/66.0MB downloaded

[==========================------------------------] 52.0% 34.3/66.0MB downloaded

[==========================------------------------] 52.1% 34.3/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.1% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.4/66.0MB downloaded

[==========================------------------------] 52.2% 34.5/66.0MB downloaded

[==========================------------------------] 52.2% 34.5/66.0MB downloaded

[==========================------------------------] 52.2% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.3% 34.5/66.0MB downloaded

[==========================------------------------] 52.4% 34.5/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.4% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.6/66.0MB downloaded

[==========================------------------------] 52.5% 34.7/66.0MB downloaded

[==========================------------------------] 52.5% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.6% 34.7/66.0MB downloaded

[==========================------------------------] 52.7% 34.7/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.7% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.8/66.0MB downloaded

[==========================------------------------] 52.8% 34.9/66.0MB downloaded

[==========================------------------------] 52.8% 34.9/66.0MB downloaded

[==========================------------------------] 52.8% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 52.9% 34.9/66.0MB downloaded

[==========================------------------------] 53.0% 34.9/66.0MB downloaded

[==========================------------------------] 53.0% 34.9/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.0% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.0/66.0MB downloaded

[==========================------------------------] 53.1% 35.1/66.0MB downloaded

[==========================------------------------] 53.1% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.2% 35.1/66.0MB downloaded

[==========================------------------------] 53.3% 35.1/66.0MB downloaded

[==========================------------------------] 53.3% 35.1/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.3% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.2/66.0MB downloaded

[==========================------------------------] 53.4% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.5% 35.3/66.0MB downloaded

[==========================------------------------] 53.6% 35.3/66.0MB downloaded

[==========================------------------------] 53.6% 35.3/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.6% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.4/66.0MB downloaded

[==========================------------------------] 53.7% 35.5/66.0MB downloaded

[==========================------------------------] 53.7% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.8% 35.5/66.0MB downloaded

[==========================------------------------] 53.9% 35.5/66.0MB downloaded

[==========================------------------------] 53.9% 35.5/66.0MB downloaded

[==========================------------------------] 53.9% 35.5/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 53.9% 35.6/66.0MB downloaded

[==========================------------------------] 54.0% 35.6/66.0MB downloaded

[==========================------------------------] 54.0% 35.6/66.0MB downloaded

[==========================------------------------] 54.0% 35.6/66.0MB downloaded

[==========================------------------------] 54.0% 35.6/66.0MB downloaded

[===========================-----------------------] 54.0% 35.6/66.0MB downloaded

[===========================-----------------------] 54.0% 35.6/66.0MB downloaded

[===========================-----------------------] 54.0% 35.6/66.0MB downloaded

[===========================-----------------------] 54.0% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.1% 35.7/66.0MB downloaded

[===========================-----------------------] 54.2% 35.7/66.0MB downloaded

[===========================-----------------------] 54.2% 35.7/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.2% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.8/66.0MB downloaded

[===========================-----------------------] 54.3% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.4% 35.9/66.0MB downloaded

[===========================-----------------------] 54.5% 35.9/66.0MB downloaded

[===========================-----------------------] 54.5% 35.9/66.0MB downloaded

[===========================-----------------------] 54.5% 35.9/66.0MB downloaded

[===========================-----------------------] 54.5% 36.0/66.0MB downloaded

[===========================-----------------------] 54.5% 36.0/66.0MB downloaded

[===========================-----------------------] 54.5% 36.0/66.0MB downloaded

[===========================-----------------------] 54.5% 36.0/66.0MB downloaded

[===========================-----------------------] 54.5% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.0/66.0MB downloaded

[===========================-----------------------] 54.6% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.7% 36.1/66.0MB downloaded

[===========================-----------------------] 54.8% 36.1/66.0MB downloaded

[===========================-----------------------] 54.8% 36.1/66.0MB downloaded

[===========================-----------------------] 54.8% 36.1/66.0MB downloaded

[===========================-----------------------] 54.8% 36.1/66.0MB downloaded

[===========================-----------------------] 54.8% 36.2/66.0MB downloaded

[===========================-----------------------] 54.8% 36.2/66.0MB downloaded

[===========================-----------------------] 54.8% 36.2/66.0MB downloaded

[===========================-----------------------] 54.8% 36.2/66.0MB downloaded

[===========================-----------------------] 54.8% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 54.9% 36.2/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.0% 36.3/66.0MB downloaded

[===========================-----------------------] 55.1% 36.3/66.0MB downloaded

[===========================-----------------------] 55.1% 36.3/66.0MB downloaded

[===========================-----------------------] 55.1% 36.3/66.0MB downloaded

[===========================-----------------------] 55.1% 36.4/66.0MB downloaded

[===========================-----------------------] 55.1% 36.4/66.0MB downloaded

[===========================-----------------------] 55.1% 36.4/66.0MB downloaded

[===========================-----------------------] 55.1% 36.4/66.0MB downloaded

[===========================-----------------------] 55.1% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.2% 36.4/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.3% 36.5/66.0MB downloaded

[===========================-----------------------] 55.4% 36.5/66.0MB downloaded

[===========================-----------------------] 55.4% 36.5/66.0MB downloaded

[===========================-----------------------] 55.4% 36.5/66.0MB downloaded

[===========================-----------------------] 55.4% 36.5/66.0MB downloaded

[===========================-----------------------] 55.4% 36.6/66.0MB downloaded

[===========================-----------------------] 55.4% 36.6/66.0MB downloaded

[===========================-----------------------] 55.4% 36.6/66.0MB downloaded

[===========================-----------------------] 55.4% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.5% 36.6/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.6% 36.7/66.0MB downloaded

[===========================-----------------------] 55.7% 36.7/66.0MB downloaded

[===========================-----------------------] 55.7% 36.7/66.0MB downloaded

[===========================-----------------------] 55.7% 36.7/66.0MB downloaded

[===========================-----------------------] 55.7% 36.7/66.0MB downloaded

[===========================-----------------------] 55.7% 36.8/66.0MB downloaded

[===========================-----------------------] 55.7% 36.8/66.0MB downloaded

[===========================-----------------------] 55.7% 36.8/66.0MB downloaded

[===========================-----------------------] 55.7% 36.8/66.0MB downloaded

[===========================-----------------------] 55.7% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.8% 36.8/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 55.9% 36.9/66.0MB downloaded

[===========================-----------------------] 56.0% 36.9/66.0MB downloaded

[===========================-----------------------] 56.0% 36.9/66.0MB downloaded

[===========================-----------------------] 56.0% 36.9/66.0MB downloaded

[===========================-----------------------] 56.0% 36.9/66.0MB downloaded

[============================----------------------] 56.0% 37.0/66.0MB downloaded

[============================----------------------] 56.0% 37.0/66.0MB downloaded

[============================----------------------] 56.0% 37.0/66.0MB downloaded

[============================----------------------] 56.0% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.1% 37.0/66.0MB downloaded

[============================----------------------] 56.2% 37.0/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.2% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.1/66.0MB downloaded

[============================----------------------] 56.3% 37.2/66.0MB downloaded

[============================----------------------] 56.3% 37.2/66.0MB downloaded

[============================----------------------] 56.3% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.4% 37.2/66.0MB downloaded

[============================----------------------] 56.5% 37.2/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.5% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.3/66.0MB downloaded

[============================----------------------] 56.6% 37.4/66.0MB downloaded

[============================----------------------] 56.6% 37.4/66.0MB downloaded

[============================----------------------] 56.6% 37.4/66.0MB downloaded

[============================----------------------] 56.6% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.7% 37.4/66.0MB downloaded

[============================----------------------] 56.8% 37.4/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.8% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.5/66.0MB downloaded

[============================----------------------] 56.9% 37.6/66.0MB downloaded

[============================----------------------] 56.9% 37.6/66.0MB downloaded

[============================----------------------] 56.9% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.0% 37.6/66.0MB downloaded

[============================----------------------] 57.1% 37.6/66.0MB downloaded

[============================----------------------] 57.1% 37.6/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.1% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.7/66.0MB downloaded

[============================----------------------] 57.2% 37.8/66.0MB downloaded

[============================----------------------] 57.2% 37.8/66.0MB downloaded

[============================----------------------] 57.2% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.3% 37.8/66.0MB downloaded

[============================----------------------] 57.4% 37.8/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.4% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 37.9/66.0MB downloaded

[============================----------------------] 57.5% 38.0/66.0MB downloaded

[============================----------------------] 57.5% 38.0/66.0MB downloaded

[============================----------------------] 57.5% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.6% 38.0/66.0MB downloaded

[============================----------------------] 57.7% 38.0/66.0MB downloaded

[============================----------------------] 57.7% 38.0/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.7% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.1/66.0MB downloaded

[============================----------------------] 57.8% 38.2/66.0MB downloaded

[============================----------------------] 57.8% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 57.9% 38.2/66.0MB downloaded

[============================----------------------] 58.0% 38.2/66.0MB downloaded

[============================----------------------] 58.0% 38.2/66.0MB downloaded

[============================----------------------] 58.0% 38.2/66.0MB downloaded

[============================----------------------] 58.0% 38.3/66.0MB downloaded

[============================----------------------] 58.0% 38.3/66.0MB downloaded

[=============================---------------------] 58.0% 38.3/66.0MB downloaded

[=============================---------------------] 58.0% 38.3/66.0MB downloaded

[=============================---------------------] 58.0% 38.3/66.0MB downloaded

[=============================---------------------] 58.0% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.3/66.0MB downloaded

[=============================---------------------] 58.1% 38.4/66.0MB downloaded

[=============================---------------------] 58.1% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.2% 38.4/66.0MB downloaded

[=============================---------------------] 58.3% 38.4/66.0MB downloaded

[=============================---------------------] 58.3% 38.4/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.3% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.5/66.0MB downloaded

[=============================---------------------] 58.4% 38.6/66.0MB downloaded

[=============================---------------------] 58.4% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.5% 38.6/66.0MB downloaded

[=============================---------------------] 58.6% 38.6/66.0MB downloaded

[=============================---------------------] 58.6% 38.6/66.0MB downloaded

[=============================---------------------] 58.6% 38.6/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.6% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.7/66.0MB downloaded

[=============================---------------------] 58.7% 38.8/66.0MB downloaded

[=============================---------------------] 58.7% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.8% 38.8/66.0MB downloaded

[=============================---------------------] 58.9% 38.8/66.0MB downloaded

[=============================---------------------] 58.9% 38.8/66.0MB downloaded

[=============================---------------------] 58.9% 38.8/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 58.9% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 38.9/66.0MB downloaded

[=============================---------------------] 59.0% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.1% 39.0/66.0MB downloaded

[=============================---------------------] 59.2% 39.0/66.0MB downloaded

[=============================---------------------] 59.2% 39.0/66.0MB downloaded

[=============================---------------------] 59.2% 39.0/66.0MB downloaded

[=============================---------------------] 59.2% 39.1/66.0MB downloaded

[=============================---------------------] 59.2% 39.1/66.0MB downloaded

[=============================---------------------] 59.2% 39.1/66.0MB downloaded

[=============================---------------------] 59.2% 39.1/66.0MB downloaded

[=============================---------------------] 59.2% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.1/66.0MB downloaded

[=============================---------------------] 59.3% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.4% 39.2/66.0MB downloaded

[=============================---------------------] 59.5% 39.2/66.0MB downloaded

[=============================---------------------] 59.5% 39.2/66.0MB downloaded

[=============================---------------------] 59.5% 39.2/66.0MB downloaded

[=============================---------------------] 59.5% 39.2/66.0MB downloaded

[=============================---------------------] 59.5% 39.3/66.0MB downloaded

[=============================---------------------] 59.5% 39.3/66.0MB downloaded

[=============================---------------------] 59.5% 39.3/66.0MB downloaded

[=============================---------------------] 59.5% 39.3/66.0MB downloaded

[=============================---------------------] 59.5% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.3/66.0MB downloaded

[=============================---------------------] 59.6% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.7% 39.4/66.0MB downloaded

[=============================---------------------] 59.8% 39.4/66.0MB downloaded

[=============================---------------------] 59.8% 39.4/66.0MB downloaded

[=============================---------------------] 59.8% 39.4/66.0MB downloaded

[=============================---------------------] 59.8% 39.4/66.0MB downloaded

[=============================---------------------] 59.8% 39.5/66.0MB downloaded

[=============================---------------------] 59.8% 39.5/66.0MB downloaded

[=============================---------------------] 59.8% 39.5/66.0MB downloaded

[=============================---------------------] 59.8% 39.5/66.0MB downloaded

[=============================---------------------] 59.8% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 59.9% 39.5/66.0MB downloaded

[=============================---------------------] 60.0% 39.6/66.0MB downloaded

[=============================---------------------] 60.0% 39.6/66.0MB downloaded

[=============================---------------------] 60.0% 39.6/66.0MB downloaded

[=============================---------------------] 60.0% 39.6/66.0MB downloaded

[=============================---------------------] 60.0% 39.6/66.0MB downloaded

[==============================--------------------] 60.0% 39.6/66.0MB downloaded

[==============================--------------------] 60.0% 39.6/66.0MB downloaded

[==============================--------------------] 60.0% 39.6/66.0MB downloaded

[==============================--------------------] 60.0% 39.6/66.0MB downloaded

[==============================--------------------] 60.1% 39.6/66.0MB downloaded

[==============================--------------------] 60.1% 39.6/66.0MB downloaded

[==============================--------------------] 60.1% 39.6/66.0MB downloaded

[==============================--------------------] 60.1% 39.6/66.0MB downloaded

[==============================--------------------] 60.1% 39.7/66.0MB downloaded

[==============================--------------------] 60.1% 39.7/66.0MB downloaded

[==============================--------------------] 60.1% 39.7/66.0MB downloaded

[==============================--------------------] 60.1% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.7/66.0MB downloaded

[==============================--------------------] 60.2% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.3% 39.8/66.0MB downloaded

[==============================--------------------] 60.4% 39.8/66.0MB downloaded

[==============================--------------------] 60.4% 39.8/66.0MB downloaded

[==============================--------------------] 60.4% 39.8/66.0MB downloaded

[==============================--------------------] 60.4% 39.8/66.0MB downloaded

[==============================--------------------] 60.4% 39.9/66.0MB downloaded

[==============================--------------------] 60.4% 39.9/66.0MB downloaded

[==============================--------------------] 60.4% 39.9/66.0MB downloaded

[==============================--------------------] 60.4% 39.9/66.0MB downloaded

[==============================--------------------] 60.4% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.5% 39.9/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.6% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.0/66.0MB downloaded

[==============================--------------------] 60.7% 40.1/66.0MB downloaded

[==============================--------------------] 60.7% 40.1/66.0MB downloaded

[==============================--------------------] 60.7% 40.1/66.0MB downloaded

[==============================--------------------] 60.7% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.8% 40.1/66.0MB downloaded

[==============================--------------------] 60.9% 40.1/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 60.9% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.2/66.0MB downloaded

[==============================--------------------] 61.0% 40.3/66.0MB downloaded

[==============================--------------------] 61.0% 40.3/66.0MB downloaded

[==============================--------------------] 61.0% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.1% 40.3/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.2% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.4/66.0MB downloaded

[==============================--------------------] 61.3% 40.5/66.0MB downloaded

[==============================--------------------] 61.3% 40.5/66.0MB downloaded

[==============================--------------------] 61.3% 40.5/66.0MB downloaded

[==============================--------------------] 61.3% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.4% 40.5/66.0MB downloaded

[==============================--------------------] 61.5% 40.5/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.5% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.6/66.0MB downloaded

[==============================--------------------] 61.6% 40.7/66.0MB downloaded

[==============================--------------------] 61.6% 40.7/66.0MB downloaded

[==============================--------------------] 61.6% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.7% 40.7/66.0MB downloaded

[==============================--------------------] 61.8% 40.7/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.8% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.8/66.0MB downloaded

[==============================--------------------] 61.9% 40.9/66.0MB downloaded

[==============================--------------------] 61.9% 40.9/66.0MB downloaded

[==============================--------------------] 61.9% 40.9/66.0MB downloaded

[==============================--------------------] 62.0% 40.9/66.0MB downloaded

[==============================--------------------] 62.0% 40.9/66.0MB downloaded

[==============================--------------------] 62.0% 40.9/66.0MB downloaded

[==============================--------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.0% 40.9/66.0MB downloaded

[===============================-------------------] 62.1% 40.9/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.1% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.0/66.0MB downloaded

[===============================-------------------] 62.2% 41.1/66.0MB downloaded

[===============================-------------------] 62.2% 41.1/66.0MB downloaded

[===============================-------------------] 62.2% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.3% 41.1/66.0MB downloaded

[===============================-------------------] 62.4% 41.1/66.0MB downloaded

[===============================-------------------] 62.4% 41.1/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.4% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.2/66.0MB downloaded

[===============================-------------------] 62.5% 41.3/66.0MB downloaded

[===============================-------------------] 62.5% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.6% 41.3/66.0MB downloaded

[===============================-------------------] 62.7% 41.3/66.0MB downloaded

[===============================-------------------] 62.7% 41.3/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.7% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.4/66.0MB downloaded

[===============================-------------------] 62.8% 41.5/66.0MB downloaded

[===============================-------------------] 62.8% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 62.9% 41.5/66.0MB downloaded

[===============================-------------------] 63.0% 41.5/66.0MB downloaded

[===============================-------------------] 63.0% 41.5/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.0% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.6/66.0MB downloaded

[===============================-------------------] 63.1% 41.7/66.0MB downloaded

[===============================-------------------] 63.1% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.2% 41.7/66.0MB downloaded

[===============================-------------------] 63.3% 41.7/66.0MB downloaded

[===============================-------------------] 63.3% 41.7/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.3% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.8/66.0MB downloaded

[===============================-------------------] 63.4% 41.9/66.0MB downloaded

[===============================-------------------] 63.4% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.5% 41.9/66.0MB downloaded

[===============================-------------------] 63.6% 41.9/66.0MB downloaded

[===============================-------------------] 63.6% 41.9/66.0MB downloaded

[===============================-------------------] 63.6% 41.9/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.6% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.0/66.0MB downloaded

[===============================-------------------] 63.7% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.8% 42.1/66.0MB downloaded

[===============================-------------------] 63.9% 42.1/66.0MB downloaded

[===============================-------------------] 63.9% 42.1/66.0MB downloaded

[===============================-------------------] 63.9% 42.1/66.0MB downloaded

[===============================-------------------] 63.9% 42.2/66.0MB downloaded

[===============================-------------------] 63.9% 42.2/66.0MB downloaded

[===============================-------------------] 63.9% 42.2/66.0MB downloaded

[===============================-------------------] 63.9% 42.2/66.0MB downloaded

[===============================-------------------] 63.9% 42.2/66.0MB downloaded

[===============================-------------------] 64.0% 42.2/66.0MB downloaded

[===============================-------------------] 64.0% 42.2/66.0MB downloaded

[===============================-------------------] 64.0% 42.2/66.0MB downloaded

[===============================-------------------] 64.0% 42.2/66.0MB downloaded

[================================------------------] 64.0% 42.2/66.0MB downloaded

[================================------------------] 64.0% 42.2/66.0MB downloaded

[================================------------------] 64.0% 42.2/66.0MB downloaded

[================================------------------] 64.0% 42.2/66.0MB downloaded

[================================------------------] 64.0% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.1% 42.3/66.0MB downloaded

[================================------------------] 64.2% 42.3/66.0MB downloaded

[================================------------------] 64.2% 42.3/66.0MB downloaded

[================================------------------] 64.2% 42.3/66.0MB downloaded

[================================------------------] 64.2% 42.4/66.0MB downloaded

[================================------------------] 64.2% 42.4/66.0MB downloaded

[================================------------------] 64.2% 42.4/66.0MB downloaded

[================================------------------] 64.2% 42.4/66.0MB downloaded

[================================------------------] 64.2% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.4/66.0MB downloaded

[================================------------------] 64.3% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.4% 42.5/66.0MB downloaded

[================================------------------] 64.5% 42.5/66.0MB downloaded

[================================------------------] 64.5% 42.5/66.0MB downloaded

[================================------------------] 64.5% 42.5/66.0MB downloaded

[================================------------------] 64.5% 42.5/66.0MB downloaded

[================================------------------] 64.5% 42.6/66.0MB downloaded

[================================------------------] 64.5% 42.6/66.0MB downloaded

[================================------------------] 64.5% 42.6/66.0MB downloaded

[================================------------------] 64.5% 42.6/66.0MB downloaded

[================================------------------] 64.5% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.6% 42.6/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.7% 42.7/66.0MB downloaded

[================================------------------] 64.8% 42.7/66.0MB downloaded

[================================------------------] 64.8% 42.7/66.0MB downloaded

[================================------------------] 64.8% 42.7/66.0MB downloaded

[================================------------------] 64.8% 42.8/66.0MB downloaded

[================================------------------] 64.8% 42.8/66.0MB downloaded

[================================------------------] 64.8% 42.8/66.0MB downloaded

[================================------------------] 64.8% 42.8/66.0MB downloaded

[================================------------------] 64.8% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.8/66.0MB downloaded

[================================------------------] 64.9% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.0% 42.9/66.0MB downloaded

[================================------------------] 65.1% 42.9/66.0MB downloaded

[================================------------------] 65.1% 42.9/66.0MB downloaded

[================================------------------] 65.1% 42.9/66.0MB downloaded

[================================------------------] 65.1% 42.9/66.0MB downloaded

[================================------------------] 65.1% 43.0/66.0MB downloaded

[================================------------------] 65.1% 43.0/66.0MB downloaded

[================================------------------] 65.1% 43.0/66.0MB downloaded

[================================------------------] 65.1% 43.0/66.0MB downloaded

[================================------------------] 65.1% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.2% 43.0/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.3% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.1/66.0MB downloaded

[================================------------------] 65.4% 43.2/66.0MB downloaded

[================================------------------] 65.4% 43.2/66.0MB downloaded

[================================------------------] 65.4% 43.2/66.0MB downloaded

[================================------------------] 65.4% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.5% 43.2/66.0MB downloaded

[================================------------------] 65.6% 43.2/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.6% 43.3/66.0MB downloaded

[================================------------------] 65.7% 43.3/66.0MB downloaded

[================================------------------] 65.7% 43.3/66.0MB downloaded

[================================------------------] 65.7% 43.3/66.0MB downloaded

[================================------------------] 65.7% 43.3/66.0MB downloaded

[================================------------------] 65.7% 43.4/66.0MB downloaded

[================================------------------] 65.7% 43.4/66.0MB downloaded

[================================------------------] 65.7% 43.4/66.0MB downloaded

[================================------------------] 65.7% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.8% 43.4/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 65.9% 43.5/66.0MB downloaded

[================================------------------] 66.0% 43.5/66.0MB downloaded

[================================------------------] 66.0% 43.5/66.0MB downloaded

[================================------------------] 66.0% 43.5/66.0MB downloaded

[================================------------------] 66.0% 43.5/66.0MB downloaded

[=================================-----------------] 66.0% 43.5/66.0MB downloaded

[=================================-----------------] 66.0% 43.6/66.0MB downloaded

[=================================-----------------] 66.0% 43.6/66.0MB downloaded

[=================================-----------------] 66.0% 43.6/66.0MB downloaded

[=================================-----------------] 66.0% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.1% 43.6/66.0MB downloaded

[=================================-----------------] 66.2% 43.6/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.2% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.7/66.0MB downloaded

[=================================-----------------] 66.3% 43.8/66.0MB downloaded

[=================================-----------------] 66.3% 43.8/66.0MB downloaded

[=================================-----------------] 66.3% 43.8/66.0MB downloaded

[=================================-----------------] 66.3% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.4% 43.8/66.0MB downloaded

[=================================-----------------] 66.5% 43.8/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.5% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 43.9/66.0MB downloaded

[=================================-----------------] 66.6% 44.0/66.0MB downloaded

[=================================-----------------] 66.6% 44.0/66.0MB downloaded

[=================================-----------------] 66.6% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.7% 44.0/66.0MB downloaded

[=================================-----------------] 66.8% 44.0/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.8% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.1/66.0MB downloaded

[=================================-----------------] 66.9% 44.2/66.0MB downloaded

[=================================-----------------] 66.9% 44.2/66.0MB downloaded

[=================================-----------------] 66.9% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.0% 44.2/66.0MB downloaded

[=================================-----------------] 67.1% 44.2/66.0MB downloaded

[=================================-----------------] 67.1% 44.2/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.1% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.3/66.0MB downloaded

[=================================-----------------] 67.2% 44.4/66.0MB downloaded

[=================================-----------------] 67.2% 44.4/66.0MB downloaded

[=================================-----------------] 67.2% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.3% 44.4/66.0MB downloaded

[=================================-----------------] 67.4% 44.4/66.0MB downloaded

[=================================-----------------] 67.4% 44.4/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.4% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.5/66.0MB downloaded

[=================================-----------------] 67.5% 44.6/66.0MB downloaded

[=================================-----------------] 67.5% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.6% 44.6/66.0MB downloaded

[=================================-----------------] 67.7% 44.6/66.0MB downloaded

[=================================-----------------] 67.7% 44.6/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.7% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.7/66.0MB downloaded

[=================================-----------------] 67.8% 44.8/66.0MB downloaded

[=================================-----------------] 67.8% 44.8/66.0MB downloaded

[=================================-----------------] 67.8% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 67.9% 44.8/66.0MB downloaded

[=================================-----------------] 68.0% 44.8/66.0MB downloaded

[=================================-----------------] 68.0% 44.8/66.0MB downloaded

[=================================-----------------] 68.0% 44.9/66.0MB downloaded

[=================================-----------------] 68.0% 44.9/66.0MB downloaded

[==================================----------------] 68.0% 44.9/66.0MB downloaded

[==================================----------------] 68.0% 44.9/66.0MB downloaded

[==================================----------------] 68.0% 44.9/66.0MB downloaded

[==================================----------------] 68.0% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 44.9/66.0MB downloaded

[==================================----------------] 68.1% 45.0/66.0MB downloaded

[==================================----------------] 68.1% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.2% 45.0/66.0MB downloaded

[==================================----------------] 68.3% 45.0/66.0MB downloaded

[==================================----------------] 68.3% 45.0/66.0MB downloaded

[==================================----------------] 68.3% 45.0/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.3% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.1/66.0MB downloaded

[==================================----------------] 68.4% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.5% 45.2/66.0MB downloaded

[==================================----------------] 68.6% 45.2/66.0MB downloaded

[==================================----------------] 68.6% 45.2/66.0MB downloaded

[==================================----------------] 68.6% 45.2/66.0MB downloaded

[==================================----------------] 68.6% 45.3/66.0MB downloaded

[==================================----------------] 68.6% 45.3/66.0MB downloaded

[==================================----------------] 68.6% 45.3/66.0MB downloaded

[==================================----------------] 68.6% 45.3/66.0MB downloaded

[==================================----------------] 68.6% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.3/66.0MB downloaded

[==================================----------------] 68.7% 45.4/66.0MB downloaded

[==================================----------------] 68.7% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.8% 45.4/66.0MB downloaded

[==================================----------------] 68.9% 45.4/66.0MB downloaded

[==================================----------------] 68.9% 45.4/66.0MB downloaded

[==================================----------------] 68.9% 45.4/66.0MB downloaded

[==================================----------------] 68.9% 45.5/66.0MB downloaded

[==================================----------------] 68.9% 45.5/66.0MB downloaded

[==================================----------------] 68.9% 45.5/66.0MB downloaded

[==================================----------------] 68.9% 45.5/66.0MB downloaded

[==================================----------------] 68.9% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.5/66.0MB downloaded

[==================================----------------] 69.0% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.1% 45.6/66.0MB downloaded

[==================================----------------] 69.2% 45.6/66.0MB downloaded

[==================================----------------] 69.2% 45.6/66.0MB downloaded

[==================================----------------] 69.2% 45.6/66.0MB downloaded

[==================================----------------] 69.2% 45.6/66.0MB downloaded

[==================================----------------] 69.2% 45.7/66.0MB downloaded

[==================================----------------] 69.2% 45.7/66.0MB downloaded

[==================================----------------] 69.2% 45.7/66.0MB downloaded

[==================================----------------] 69.2% 45.7/66.0MB downloaded

[==================================----------------] 69.2% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.7/66.0MB downloaded

[==================================----------------] 69.3% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.4% 45.8/66.0MB downloaded

[==================================----------------] 69.5% 45.8/66.0MB downloaded

[==================================----------------] 69.5% 45.8/66.0MB downloaded

[==================================----------------] 69.5% 45.8/66.0MB downloaded

[==================================----------------] 69.5% 45.9/66.0MB downloaded

[==================================----------------] 69.5% 45.9/66.0MB downloaded

[==================================----------------] 69.5% 45.9/66.0MB downloaded

[==================================----------------] 69.5% 45.9/66.0MB downloaded

[==================================----------------] 69.5% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 45.9/66.0MB downloaded

[==================================----------------] 69.6% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.7% 46.0/66.0MB downloaded

[==================================----------------] 69.8% 46.0/66.0MB downloaded

[==================================----------------] 69.8% 46.0/66.0MB downloaded

[==================================----------------] 69.8% 46.0/66.0MB downloaded

[==================================----------------] 69.8% 46.0/66.0MB downloaded

[==================================----------------] 69.8% 46.1/66.0MB downloaded

[==================================----------------] 69.8% 46.1/66.0MB downloaded

[==================================----------------] 69.8% 46.1/66.0MB downloaded

[==================================----------------] 69.8% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 69.9% 46.1/66.0MB downloaded

[==================================----------------] 70.0% 46.2/66.0MB downloaded

[==================================----------------] 70.0% 46.2/66.0MB downloaded

[==================================----------------] 70.0% 46.2/66.0MB downloaded

[==================================----------------] 70.0% 46.2/66.0MB downloaded

[===================================---------------] 70.0% 46.2/66.0MB downloaded

[===================================---------------] 70.0% 46.2/66.0MB downloaded

[===================================---------------] 70.0% 46.2/66.0MB downloaded

[===================================---------------] 70.0% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.2/66.0MB downloaded

[===================================---------------] 70.1% 46.3/66.0MB downloaded

[===================================---------------] 70.1% 46.3/66.0MB downloaded

[===================================---------------] 70.1% 46.3/66.0MB downloaded

[===================================---------------] 70.1% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.2% 46.3/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.3% 46.4/66.0MB downloaded

[===================================---------------] 70.4% 46.4/66.0MB downloaded

[===================================---------------] 70.4% 46.4/66.0MB downloaded

[===================================---------------] 70.4% 46.4/66.0MB downloaded

[===================================---------------] 70.4% 46.4/66.0MB downloaded

[===================================---------------] 70.4% 46.5/66.0MB downloaded

[===================================---------------] 70.4% 46.5/66.0MB downloaded

[===================================---------------] 70.4% 46.5/66.0MB downloaded

[===================================---------------] 70.4% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.5% 46.5/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.6% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.6/66.0MB downloaded

[===================================---------------] 70.7% 46.7/66.0MB downloaded

[===================================---------------] 70.7% 46.7/66.0MB downloaded

[===================================---------------] 70.7% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.8% 46.7/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 70.9% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.8/66.0MB downloaded

[===================================---------------] 71.0% 46.9/66.0MB downloaded

[===================================---------------] 71.0% 46.9/66.0MB downloaded

[===================================---------------] 71.0% 46.9/66.0MB downloaded

[===================================---------------] 71.0% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.1% 46.9/66.0MB downloaded

[===================================---------------] 71.2% 46.9/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.2% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.0/66.0MB downloaded

[===================================---------------] 71.3% 47.1/66.0MB downloaded

[===================================---------------] 71.3% 47.1/66.0MB downloaded

[===================================---------------] 71.3% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.4% 47.1/66.0MB downloaded

[===================================---------------] 71.5% 47.1/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.5% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.2/66.0MB downloaded

[===================================---------------] 71.6% 47.3/66.0MB downloaded

[===================================---------------] 71.6% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.7% 47.3/66.0MB downloaded

[===================================---------------] 71.8% 47.3/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.8% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.4/66.0MB downloaded

[===================================---------------] 71.9% 47.5/66.0MB downloaded

[===================================---------------] 71.9% 47.5/66.0MB downloaded

[===================================---------------] 71.9% 47.5/66.0MB downloaded

[===================================---------------] 72.0% 47.5/66.0MB downloaded

[===================================---------------] 72.0% 47.5/66.0MB downloaded

[===================================---------------] 72.0% 47.5/66.0MB downloaded

[===================================---------------] 72.0% 47.5/66.0MB downloaded

[====================================--------------] 72.0% 47.5/66.0MB downloaded

[====================================--------------] 72.0% 47.5/66.0MB downloaded

[====================================--------------] 72.0% 47.5/66.0MB downloaded

[====================================--------------] 72.0% 47.5/66.0MB downloaded

[====================================--------------] 72.1% 47.5/66.0MB downloaded

[====================================--------------] 72.1% 47.5/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.1% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.6/66.0MB downloaded

[====================================--------------] 72.2% 47.7/66.0MB downloaded

[====================================--------------] 72.2% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.3% 47.7/66.0MB downloaded

[====================================--------------] 72.4% 47.7/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.4% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.8/66.0MB downloaded

[====================================--------------] 72.5% 47.9/66.0MB downloaded

[====================================--------------] 72.5% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.6% 47.9/66.0MB downloaded

[====================================--------------] 72.7% 47.9/66.0MB downloaded

[====================================--------------] 72.7% 47.9/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.7% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.0/66.0MB downloaded

[====================================--------------] 72.8% 48.1/66.0MB downloaded

[====================================--------------] 72.8% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 72.9% 48.1/66.0MB downloaded

[====================================--------------] 73.0% 48.1/66.0MB downloaded

[====================================--------------] 73.0% 48.1/66.0MB downloaded

[====================================--------------] 73.0% 48.1/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.0% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.2/66.0MB downloaded

[====================================--------------] 73.1% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.2% 48.3/66.0MB downloaded

[====================================--------------] 73.3% 48.3/66.0MB downloaded

[====================================--------------] 73.3% 48.3/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.3% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.4/66.0MB downloaded

[====================================--------------] 73.4% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.5% 48.5/66.0MB downloaded

[====================================--------------] 73.6% 48.5/66.0MB downloaded

[====================================--------------] 73.6% 48.5/66.0MB downloaded

[====================================--------------] 73.6% 48.5/66.0MB downloaded

[====================================--------------] 73.6% 48.6/66.0MB downloaded

[====================================--------------] 73.6% 48.6/66.0MB downloaded

[====================================--------------] 73.6% 48.6/66.0MB downloaded

[====================================--------------] 73.6% 48.6/66.0MB downloaded

[====================================--------------] 73.6% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.6/66.0MB downloaded

[====================================--------------] 73.7% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.8% 48.7/66.0MB downloaded

[====================================--------------] 73.9% 48.7/66.0MB downloaded

[====================================--------------] 73.9% 48.7/66.0MB downloaded

[====================================--------------] 73.9% 48.7/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 73.9% 48.8/66.0MB downloaded

[====================================--------------] 74.0% 48.8/66.0MB downloaded

[====================================--------------] 74.0% 48.8/66.0MB downloaded

[====================================--------------] 74.0% 48.8/66.0MB downloaded

[====================================--------------] 74.0% 48.8/66.0MB downloaded

[=====================================-------------] 74.0% 48.8/66.0MB downloaded

[=====================================-------------] 74.0% 48.8/66.0MB downloaded

[=====================================-------------] 74.0% 48.8/66.0MB downloaded

[=====================================-------------] 74.0% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.1% 48.9/66.0MB downloaded

[=====================================-------------] 74.2% 48.9/66.0MB downloaded

[=====================================-------------] 74.2% 48.9/66.0MB downloaded

[=====================================-------------] 74.2% 48.9/66.0MB downloaded

[=====================================-------------] 74.2% 49.0/66.0MB downloaded

[=====================================-------------] 74.2% 49.0/66.0MB downloaded

[=====================================-------------] 74.2% 49.0/66.0MB downloaded

[=====================================-------------] 74.2% 49.0/66.0MB downloaded

[=====================================-------------] 74.2% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.3% 49.0/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.4% 49.1/66.0MB downloaded

[=====================================-------------] 74.5% 49.1/66.0MB downloaded

[=====================================-------------] 74.5% 49.1/66.0MB downloaded

[=====================================-------------] 74.5% 49.1/66.0MB downloaded

[=====================================-------------] 74.5% 49.1/66.0MB downloaded

[=====================================-------------] 74.5% 49.2/66.0MB downloaded

[=====================================-------------] 74.5% 49.2/66.0MB downloaded

[=====================================-------------] 74.5% 49.2/66.0MB downloaded

[=====================================-------------] 74.5% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.6% 49.2/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.7% 49.3/66.0MB downloaded

[=====================================-------------] 74.8% 49.3/66.0MB downloaded

[=====================================-------------] 74.8% 49.3/66.0MB downloaded

[=====================================-------------] 74.8% 49.3/66.0MB downloaded

[=====================================-------------] 74.8% 49.3/66.0MB downloaded

[=====================================-------------] 74.8% 49.4/66.0MB downloaded

[=====================================-------------] 74.8% 49.4/66.0MB downloaded

[=====================================-------------] 74.8% 49.4/66.0MB downloaded

[=====================================-------------] 74.8% 49.4/66.0MB downloaded

[=====================================-------------] 74.8% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 74.9% 49.4/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.0% 49.5/66.0MB downloaded

[=====================================-------------] 75.1% 49.5/66.0MB downloaded

[=====================================-------------] 75.1% 49.5/66.0MB downloaded

[=====================================-------------] 75.1% 49.5/66.0MB downloaded

[=====================================-------------] 75.1% 49.5/66.0MB downloaded

[=====================================-------------] 75.1% 49.6/66.0MB downloaded

[=====================================-------------] 75.1% 49.6/66.0MB downloaded

[=====================================-------------] 75.1% 49.6/66.0MB downloaded

[=====================================-------------] 75.1% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.2% 49.6/66.0MB downloaded

[=====================================-------------] 75.3% 49.6/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.3% 49.7/66.0MB downloaded

[=====================================-------------] 75.4% 49.7/66.0MB downloaded

[=====================================-------------] 75.4% 49.7/66.0MB downloaded

[=====================================-------------] 75.4% 49.7/66.0MB downloaded

[=====================================-------------] 75.4% 49.7/66.0MB downloaded

[=====================================-------------] 75.4% 49.8/66.0MB downloaded

[=====================================-------------] 75.4% 49.8/66.0MB downloaded

[=====================================-------------] 75.4% 49.8/66.0MB downloaded

[=====================================-------------] 75.4% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.5% 49.8/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.6% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 49.9/66.0MB downloaded

[=====================================-------------] 75.7% 50.0/66.0MB downloaded

[=====================================-------------] 75.7% 50.0/66.0MB downloaded

[=====================================-------------] 75.7% 50.0/66.0MB downloaded

[=====================================-------------] 75.7% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.8% 50.0/66.0MB downloaded

[=====================================-------------] 75.9% 50.0/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 75.9% 50.1/66.0MB downloaded

[=====================================-------------] 76.0% 50.1/66.0MB downloaded

[=====================================-------------] 76.0% 50.1/66.0MB downloaded

[=====================================-------------] 76.0% 50.1/66.0MB downloaded

[=====================================-------------] 76.0% 50.1/66.0MB downloaded

[======================================------------] 76.0% 50.1/66.0MB downloaded

[======================================------------] 76.0% 50.2/66.0MB downloaded

[======================================------------] 76.0% 50.2/66.0MB downloaded

[======================================------------] 76.0% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.1% 50.2/66.0MB downloaded

[======================================------------] 76.2% 50.2/66.0MB downloaded

[======================================------------] 76.2% 50.2/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.2% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.3/66.0MB downloaded

[======================================------------] 76.3% 50.4/66.0MB downloaded

[======================================------------] 76.3% 50.4/66.0MB downloaded

[======================================------------] 76.3% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.4% 50.4/66.0MB downloaded

[======================================------------] 76.5% 50.4/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.5% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.5/66.0MB downloaded

[======================================------------] 76.6% 50.6/66.0MB downloaded

[======================================------------] 76.6% 50.6/66.0MB downloaded

[======================================------------] 76.6% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.7% 50.6/66.0MB downloaded

[======================================------------] 76.8% 50.6/66.0MB downloaded

[======================================------------] 76.8% 50.6/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.8% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.7/66.0MB downloaded

[======================================------------] 76.9% 50.8/66.0MB downloaded

[======================================------------] 76.9% 50.8/66.0MB downloaded

[======================================------------] 76.9% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.0% 50.8/66.0MB downloaded

[======================================------------] 77.1% 50.8/66.0MB downloaded

[======================================------------] 77.1% 50.8/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.1% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 50.9/66.0MB downloaded

[======================================------------] 77.2% 51.0/66.0MB downloaded

[======================================------------] 77.2% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.3% 51.0/66.0MB downloaded

[======================================------------] 77.4% 51.0/66.0MB downloaded

[======================================------------] 77.4% 51.0/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.4% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.1/66.0MB downloaded

[======================================------------] 77.5% 51.2/66.0MB downloaded

[======================================------------] 77.5% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.6% 51.2/66.0MB downloaded

[======================================------------] 77.7% 51.2/66.0MB downloaded

[======================================------------] 77.7% 51.2/66.0MB downloaded

[======================================------------] 77.7% 51.2/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.7% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.3/66.0MB downloaded

[======================================------------] 77.8% 51.4/66.0MB downloaded

[======================================------------] 77.8% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 77.9% 51.4/66.0MB downloaded

[======================================------------] 78.0% 51.4/66.0MB downloaded

[======================================------------] 78.0% 51.4/66.0MB downloaded

[======================================------------] 78.0% 51.4/66.0MB downloaded

[======================================------------] 78.0% 51.5/66.0MB downloaded

[======================================------------] 78.0% 51.5/66.0MB downloaded

[=======================================-----------] 78.0% 51.5/66.0MB downloaded

[=======================================-----------] 78.0% 51.5/66.0MB downloaded

[=======================================-----------] 78.0% 51.5/66.0MB downloaded

[=======================================-----------] 78.0% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.5/66.0MB downloaded

[=======================================-----------] 78.1% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.2% 51.6/66.0MB downloaded

[=======================================-----------] 78.3% 51.6/66.0MB downloaded

[=======================================-----------] 78.3% 51.6/66.0MB downloaded

[=======================================-----------] 78.3% 51.6/66.0MB downloaded

[=======================================-----------] 78.3% 51.7/66.0MB downloaded

[=======================================-----------] 78.3% 51.7/66.0MB downloaded

[=======================================-----------] 78.3% 51.7/66.0MB downloaded

[=======================================-----------] 78.3% 51.7/66.0MB downloaded

[=======================================-----------] 78.3% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.7/66.0MB downloaded

[=======================================-----------] 78.4% 51.8/66.0MB downloaded

[=======================================-----------] 78.4% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.5% 51.8/66.0MB downloaded

[=======================================-----------] 78.6% 51.8/66.0MB downloaded

[=======================================-----------] 78.6% 51.8/66.0MB downloaded

[=======================================-----------] 78.6% 51.8/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.6% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 51.9/66.0MB downloaded

[=======================================-----------] 78.7% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.8% 52.0/66.0MB downloaded

[=======================================-----------] 78.9% 52.0/66.0MB downloaded

[=======================================-----------] 78.9% 52.0/66.0MB downloaded

[=======================================-----------] 78.9% 52.0/66.0MB downloaded

[=======================================-----------] 78.9% 52.0/66.0MB downloaded

[=======================================-----------] 78.9% 52.1/66.0MB downloaded

[=======================================-----------] 78.9% 52.1/66.0MB downloaded

[=======================================-----------] 78.9% 52.1/66.0MB downloaded

[=======================================-----------] 78.9% 52.1/66.0MB downloaded

[=======================================-----------] 78.9% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.0% 52.1/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.1% 52.2/66.0MB downloaded

[=======================================-----------] 79.2% 52.2/66.0MB downloaded

[=======================================-----------] 79.2% 52.2/66.0MB downloaded

[=======================================-----------] 79.2% 52.2/66.0MB downloaded

[=======================================-----------] 79.2% 52.2/66.0MB downloaded

[=======================================-----------] 79.2% 52.3/66.0MB downloaded

[=======================================-----------] 79.2% 52.3/66.0MB downloaded

[=======================================-----------] 79.2% 52.3/66.0MB downloaded

[=======================================-----------] 79.2% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.3/66.0MB downloaded

[=======================================-----------] 79.3% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.4% 52.4/66.0MB downloaded

[=======================================-----------] 79.5% 52.4/66.0MB downloaded

[=======================================-----------] 79.5% 52.4/66.0MB downloaded

[=======================================-----------] 79.5% 52.4/66.0MB downloaded

[=======================================-----------] 79.5% 52.4/66.0MB downloaded

[=======================================-----------] 79.5% 52.5/66.0MB downloaded

[=======================================-----------] 79.5% 52.5/66.0MB downloaded

[=======================================-----------] 79.5% 52.5/66.0MB downloaded

[=======================================-----------] 79.5% 52.5/66.0MB downloaded

[=======================================-----------] 79.5% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.6% 52.5/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.7% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.6/66.0MB downloaded

[=======================================-----------] 79.8% 52.7/66.0MB downloaded

[=======================================-----------] 79.8% 52.7/66.0MB downloaded

[=======================================-----------] 79.8% 52.7/66.0MB downloaded

[=======================================-----------] 79.8% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 79.9% 52.7/66.0MB downloaded

[=======================================-----------] 80.0% 52.8/66.0MB downloaded

[=======================================-----------] 80.0% 52.8/66.0MB downloaded

[=======================================-----------] 80.0% 52.8/66.0MB downloaded

[=======================================-----------] 80.0% 52.8/66.0MB downloaded

[=======================================-----------] 80.0% 52.8/66.0MB downloaded

[========================================----------] 80.0% 52.8/66.0MB downloaded

[========================================----------] 80.0% 52.8/66.0MB downloaded

[========================================----------] 80.0% 52.8/66.0MB downloaded

[========================================----------] 80.0% 52.8/66.0MB downloaded

[========================================----------] 80.1% 52.8/66.0MB downloaded

[========================================----------] 80.1% 52.8/66.0MB downloaded

[========================================----------] 80.1% 52.8/66.0MB downloaded

[========================================----------] 80.1% 52.8/66.0MB downloaded

[========================================----------] 80.1% 52.9/66.0MB downloaded

[========================================----------] 80.1% 52.9/66.0MB downloaded

[========================================----------] 80.1% 52.9/66.0MB downloaded

[========================================----------] 80.1% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.2% 52.9/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.3% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.0/66.0MB downloaded

[========================================----------] 80.4% 53.1/66.0MB downloaded

[========================================----------] 80.4% 53.1/66.0MB downloaded

[========================================----------] 80.4% 53.1/66.0MB downloaded

[========================================----------] 80.4% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.5% 53.1/66.0MB downloaded

[========================================----------] 80.6% 53.1/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.6% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.2/66.0MB downloaded

[========================================----------] 80.7% 53.3/66.0MB downloaded

[========================================----------] 80.7% 53.3/66.0MB downloaded

[========================================----------] 80.7% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.8% 53.3/66.0MB downloaded

[========================================----------] 80.9% 53.3/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 80.9% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.4/66.0MB downloaded

[========================================----------] 81.0% 53.5/66.0MB downloaded

[========================================----------] 81.0% 53.5/66.0MB downloaded

[========================================----------] 81.0% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.1% 53.5/66.0MB downloaded

[========================================----------] 81.2% 53.5/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.2% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.6/66.0MB downloaded

[========================================----------] 81.3% 53.7/66.0MB downloaded

[========================================----------] 81.3% 53.7/66.0MB downloaded

[========================================----------] 81.3% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.4% 53.7/66.0MB downloaded

[========================================----------] 81.5% 53.7/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.5% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.8/66.0MB downloaded

[========================================----------] 81.6% 53.9/66.0MB downloaded

[========================================----------] 81.6% 53.9/66.0MB downloaded

[========================================----------] 81.6% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.7% 53.9/66.0MB downloaded

[========================================----------] 81.8% 53.9/66.0MB downloaded

[========================================----------] 81.8% 53.9/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.8% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.0/66.0MB downloaded

[========================================----------] 81.9% 54.1/66.0MB downloaded

[========================================----------] 81.9% 54.1/66.0MB downloaded

[========================================----------] 82.0% 54.1/66.0MB downloaded

[========================================----------] 82.0% 54.1/66.0MB downloaded

[========================================----------] 82.0% 54.1/66.0MB downloaded

[========================================----------] 82.0% 54.1/66.0MB downloaded

[========================================----------] 82.0% 54.1/66.0MB downloaded

[=========================================---------] 82.0% 54.1/66.0MB downloaded

[=========================================---------] 82.0% 54.1/66.0MB downloaded

[=========================================---------] 82.0% 54.1/66.0MB downloaded

[=========================================---------] 82.0% 54.1/66.0MB downloaded

[=========================================---------] 82.1% 54.1/66.0MB downloaded

[=========================================---------] 82.1% 54.1/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.1% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.2/66.0MB downloaded

[=========================================---------] 82.2% 54.3/66.0MB downloaded

[=========================================---------] 82.2% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.3% 54.3/66.0MB downloaded

[=========================================---------] 82.4% 54.3/66.0MB downloaded

[=========================================---------] 82.4% 54.3/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.4% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.4/66.0MB downloaded

[=========================================---------] 82.5% 54.5/66.0MB downloaded

[=========================================---------] 82.5% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.6% 54.5/66.0MB downloaded

[=========================================---------] 82.7% 54.5/66.0MB downloaded

[=========================================---------] 82.7% 54.5/66.0MB downloaded

[=========================================---------] 82.7% 54.5/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.7% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.6/66.0MB downloaded

[=========================================---------] 82.8% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 82.9% 54.7/66.0MB downloaded

[=========================================---------] 83.0% 54.7/66.0MB downloaded

[=========================================---------] 83.0% 54.7/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.0% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.8/66.0MB downloaded

[=========================================---------] 83.1% 54.9/66.0MB downloaded

[=========================================---------] 83.1% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.2% 54.9/66.0MB downloaded

[=========================================---------] 83.3% 54.9/66.0MB downloaded

[=========================================---------] 83.3% 54.9/66.0MB downloaded

[=========================================---------] 83.3% 54.9/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.3% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.0/66.0MB downloaded

[=========================================---------] 83.4% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.5% 55.1/66.0MB downloaded

[=========================================---------] 83.6% 55.1/66.0MB downloaded

[=========================================---------] 83.6% 55.1/66.0MB downloaded

[=========================================---------] 83.6% 55.1/66.0MB downloaded

[=========================================---------] 83.6% 55.1/66.0MB downloaded

[=========================================---------] 83.6% 55.2/66.0MB downloaded

[=========================================---------] 83.6% 55.2/66.0MB downloaded

[=========================================---------] 83.6% 55.2/66.0MB downloaded

[=========================================---------] 83.6% 55.2/66.0MB downloaded

[=========================================---------] 83.6% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.7% 55.2/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.8% 55.3/66.0MB downloaded

[=========================================---------] 83.9% 55.3/66.0MB downloaded

[=========================================---------] 83.9% 55.3/66.0MB downloaded

[=========================================---------] 83.9% 55.3/66.0MB downloaded

[=========================================---------] 83.9% 55.4/66.0MB downloaded

[=========================================---------] 83.9% 55.4/66.0MB downloaded

[=========================================---------] 83.9% 55.4/66.0MB downloaded

[=========================================---------] 83.9% 55.4/66.0MB downloaded

[=========================================---------] 83.9% 55.4/66.0MB downloaded

[=========================================---------] 84.0% 55.4/66.0MB downloaded

[=========================================---------] 84.0% 55.4/66.0MB downloaded

[=========================================---------] 84.0% 55.4/66.0MB downloaded

[=========================================---------] 84.0% 55.4/66.0MB downloaded

[==========================================--------] 84.0% 55.4/66.0MB downloaded

[==========================================--------] 84.0% 55.4/66.0MB downloaded

[==========================================--------] 84.0% 55.4/66.0MB downloaded

[==========================================--------] 84.0% 55.4/66.0MB downloaded

[==========================================--------] 84.0% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.1% 55.5/66.0MB downloaded

[==========================================--------] 84.2% 55.5/66.0MB downloaded

[==========================================--------] 84.2% 55.5/66.0MB downloaded

[==========================================--------] 84.2% 55.5/66.0MB downloaded

[==========================================--------] 84.2% 55.5/66.0MB downloaded

[==========================================--------] 84.2% 55.6/66.0MB downloaded

[==========================================--------] 84.2% 55.6/66.0MB downloaded

[==========================================--------] 84.2% 55.6/66.0MB downloaded

[==========================================--------] 84.2% 55.6/66.0MB downloaded

[==========================================--------] 84.2% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.3% 55.6/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.4% 55.7/66.0MB downloaded

[==========================================--------] 84.5% 55.7/66.0MB downloaded

[==========================================--------] 84.5% 55.7/66.0MB downloaded

[==========================================--------] 84.5% 55.7/66.0MB downloaded

[==========================================--------] 84.5% 55.7/66.0MB downloaded

[==========================================--------] 84.5% 55.8/66.0MB downloaded

[==========================================--------] 84.5% 55.8/66.0MB downloaded

[==========================================--------] 84.5% 55.8/66.0MB downloaded

[==========================================--------] 84.5% 55.8/66.0MB downloaded

[==========================================--------] 84.5% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.6% 55.8/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.7% 55.9/66.0MB downloaded

[==========================================--------] 84.8% 55.9/66.0MB downloaded

[==========================================--------] 84.8% 55.9/66.0MB downloaded

[==========================================--------] 84.8% 55.9/66.0MB downloaded

[==========================================--------] 84.8% 55.9/66.0MB downloaded

[==========================================--------] 84.8% 56.0/66.0MB downloaded

[==========================================--------] 84.8% 56.0/66.0MB downloaded

[==========================================--------] 84.8% 56.0/66.0MB downloaded

[==========================================--------] 84.8% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 84.9% 56.0/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.0% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.1/66.0MB downloaded

[==========================================--------] 85.1% 56.2/66.0MB downloaded

[==========================================--------] 85.1% 56.2/66.0MB downloaded

[==========================================--------] 85.1% 56.2/66.0MB downloaded

[==========================================--------] 85.1% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.2% 56.2/66.0MB downloaded

[==========================================--------] 85.3% 56.2/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.3% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.3/66.0MB downloaded

[==========================================--------] 85.4% 56.4/66.0MB downloaded

[==========================================--------] 85.4% 56.4/66.0MB downloaded

[==========================================--------] 85.4% 56.4/66.0MB downloaded

[==========================================--------] 85.4% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.5% 56.4/66.0MB downloaded

[==========================================--------] 85.6% 56.4/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.6% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.5/66.0MB downloaded

[==========================================--------] 85.7% 56.6/66.0MB downloaded

[==========================================--------] 85.7% 56.6/66.0MB downloaded

[==========================================--------] 85.7% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.8% 56.6/66.0MB downloaded

[==========================================--------] 85.9% 56.6/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 85.9% 56.7/66.0MB downloaded

[==========================================--------] 86.0% 56.7/66.0MB downloaded

[==========================================--------] 86.0% 56.7/66.0MB downloaded

[==========================================--------] 86.0% 56.7/66.0MB downloaded

[==========================================--------] 86.0% 56.7/66.0MB downloaded

[===========================================-------] 86.0% 56.7/66.0MB downloaded

[===========================================-------] 86.0% 56.8/66.0MB downloaded

[===========================================-------] 86.0% 56.8/66.0MB downloaded

[===========================================-------] 86.0% 56.8/66.0MB downloaded

[===========================================-------] 86.0% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.1% 56.8/66.0MB downloaded

[===========================================-------] 86.2% 56.8/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.2% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 56.9/66.0MB downloaded

[===========================================-------] 86.3% 57.0/66.0MB downloaded

[===========================================-------] 86.3% 57.0/66.0MB downloaded

[===========================================-------] 86.3% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.4% 57.0/66.0MB downloaded

[===========================================-------] 86.5% 57.0/66.0MB downloaded

[===========================================-------] 86.5% 57.0/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.5% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.1/66.0MB downloaded

[===========================================-------] 86.6% 57.2/66.0MB downloaded

[===========================================-------] 86.6% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.7% 57.2/66.0MB downloaded

[===========================================-------] 86.8% 57.2/66.0MB downloaded

[===========================================-------] 86.8% 57.2/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.8% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.3/66.0MB downloaded

[===========================================-------] 86.9% 57.4/66.0MB downloaded

[===========================================-------] 86.9% 57.4/66.0MB downloaded

[===========================================-------] 86.9% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.0% 57.4/66.0MB downloaded

[===========================================-------] 87.1% 57.4/66.0MB downloaded

[===========================================-------] 87.1% 57.4/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.1% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.5/66.0MB downloaded

[===========================================-------] 87.2% 57.6/66.0MB downloaded

[===========================================-------] 87.2% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.3% 57.6/66.0MB downloaded

[===========================================-------] 87.4% 57.6/66.0MB downloaded

[===========================================-------] 87.4% 57.6/66.0MB downloaded

[===========================================-------] 87.4% 57.6/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.4% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.7/66.0MB downloaded

[===========================================-------] 87.5% 57.8/66.0MB downloaded

[===========================================-------] 87.5% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.6% 57.8/66.0MB downloaded

[===========================================-------] 87.7% 57.8/66.0MB downloaded

[===========================================-------] 87.7% 57.8/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.7% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 57.9/66.0MB downloaded

[===========================================-------] 87.8% 58.0/66.0MB downloaded

[===========================================-------] 87.8% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 87.9% 58.0/66.0MB downloaded

[===========================================-------] 88.0% 58.0/66.0MB downloaded

[===========================================-------] 88.0% 58.0/66.0MB downloaded

[===========================================-------] 88.0% 58.0/66.0MB downloaded

[===========================================-------] 88.0% 58.1/66.0MB downloaded

[============================================------] 88.0% 58.1/66.0MB downloaded

[============================================------] 88.0% 58.1/66.0MB downloaded

[============================================------] 88.0% 58.1/66.0MB downloaded

[============================================------] 88.0% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.1/66.0MB downloaded

[============================================------] 88.1% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.2% 58.2/66.0MB downloaded

[============================================------] 88.3% 58.2/66.0MB downloaded

[============================================------] 88.3% 58.2/66.0MB downloaded

[============================================------] 88.3% 58.2/66.0MB downloaded

[============================================------] 88.3% 58.2/66.0MB downloaded

[============================================------] 88.3% 58.3/66.0MB downloaded

[============================================------] 88.3% 58.3/66.0MB downloaded

[============================================------] 88.3% 58.3/66.0MB downloaded

[============================================------] 88.3% 58.3/66.0MB downloaded

[============================================------] 88.3% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.3/66.0MB downloaded

[============================================------] 88.4% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.5% 58.4/66.0MB downloaded

[============================================------] 88.6% 58.4/66.0MB downloaded

[============================================------] 88.6% 58.4/66.0MB downloaded

[============================================------] 88.6% 58.4/66.0MB downloaded

[============================================------] 88.6% 58.5/66.0MB downloaded

[============================================------] 88.6% 58.5/66.0MB downloaded

[============================================------] 88.6% 58.5/66.0MB downloaded

[============================================------] 88.6% 58.5/66.0MB downloaded

[============================================------] 88.6% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.5/66.0MB downloaded

[============================================------] 88.7% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.8% 58.6/66.0MB downloaded

[============================================------] 88.9% 58.6/66.0MB downloaded

[============================================------] 88.9% 58.6/66.0MB downloaded

[============================================------] 88.9% 58.6/66.0MB downloaded

[============================================------] 88.9% 58.6/66.0MB downloaded

[============================================------] 88.9% 58.7/66.0MB downloaded

[============================================------] 88.9% 58.7/66.0MB downloaded

[============================================------] 88.9% 58.7/66.0MB downloaded

[============================================------] 88.9% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.7/66.0MB downloaded

[============================================------] 89.0% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.1% 58.8/66.0MB downloaded

[============================================------] 89.2% 58.8/66.0MB downloaded

[============================================------] 89.2% 58.8/66.0MB downloaded

[============================================------] 89.2% 58.8/66.0MB downloaded

[============================================------] 89.2% 58.8/66.0MB downloaded

[============================================------] 89.2% 58.9/66.0MB downloaded

[============================================------] 89.2% 58.9/66.0MB downloaded

[============================================------] 89.2% 58.9/66.0MB downloaded

[============================================------] 89.2% 58.9/66.0MB downloaded

[============================================------] 89.2% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.3% 58.9/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.4% 59.0/66.0MB downloaded

[============================================------] 89.5% 59.0/66.0MB downloaded

[============================================------] 89.5% 59.0/66.0MB downloaded

[============================================------] 89.5% 59.0/66.0MB downloaded

[============================================------] 89.5% 59.0/66.0MB downloaded

[============================================------] 89.5% 59.1/66.0MB downloaded

[============================================------] 89.5% 59.1/66.0MB downloaded

[============================================------] 89.5% 59.1/66.0MB downloaded

[============================================------] 89.5% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.6% 59.1/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.7% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.2/66.0MB downloaded

[============================================------] 89.8% 59.3/66.0MB downloaded

[============================================------] 89.8% 59.3/66.0MB downloaded

[============================================------] 89.8% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 89.9% 59.3/66.0MB downloaded

[============================================------] 90.0% 59.4/66.0MB downloaded

[============================================------] 90.0% 59.4/66.0MB downloaded

[============================================------] 90.0% 59.4/66.0MB downloaded

[============================================------] 90.0% 59.4/66.0MB downloaded

[=============================================-----] 90.0% 59.4/66.0MB downloaded

[=============================================-----] 90.0% 59.4/66.0MB downloaded

[=============================================-----] 90.0% 59.4/66.0MB downloaded

[=============================================-----] 90.0% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.4/66.0MB downloaded

[=============================================-----] 90.1% 59.5/66.0MB downloaded

[=============================================-----] 90.1% 59.5/66.0MB downloaded

[=============================================-----] 90.1% 59.5/66.0MB downloaded

[=============================================-----] 90.1% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.2% 59.5/66.0MB downloaded

[=============================================-----] 90.3% 59.5/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.3% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.6/66.0MB downloaded

[=============================================-----] 90.4% 59.7/66.0MB downloaded

[=============================================-----] 90.4% 59.7/66.0MB downloaded

[=============================================-----] 90.4% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.5% 59.7/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.6% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.8/66.0MB downloaded

[=============================================-----] 90.7% 59.9/66.0MB downloaded

[=============================================-----] 90.7% 59.9/66.0MB downloaded

[=============================================-----] 90.7% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.8% 59.9/66.0MB downloaded

[=============================================-----] 90.9% 59.9/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 90.9% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.0/66.0MB downloaded

[=============================================-----] 91.0% 60.1/66.0MB downloaded

[=============================================-----] 91.0% 60.1/66.0MB downloaded

[=============================================-----] 91.0% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.1% 60.1/66.0MB downloaded

[=============================================-----] 91.2% 60.1/66.0MB downloaded

[=============================================-----] 91.2% 60.1/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.2% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.2/66.0MB downloaded

[=============================================-----] 91.3% 60.3/66.0MB downloaded

[=============================================-----] 91.3% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.4% 60.3/66.0MB downloaded

[=============================================-----] 91.5% 60.3/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.5% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.4/66.0MB downloaded

[=============================================-----] 91.6% 60.5/66.0MB downloaded

[=============================================-----] 91.6% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.7% 60.5/66.0MB downloaded

[=============================================-----] 91.8% 60.5/66.0MB downloaded

[=============================================-----] 91.8% 60.5/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.8% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.6/66.0MB downloaded

[=============================================-----] 91.9% 60.7/66.0MB downloaded

[=============================================-----] 91.9% 60.7/66.0MB downloaded

[=============================================-----] 92.0% 60.7/66.0MB downloaded

[=============================================-----] 92.0% 60.7/66.0MB downloaded

[=============================================-----] 92.0% 60.7/66.0MB downloaded

[=============================================-----] 92.0% 60.7/66.0MB downloaded

[==============================================----] 92.0% 60.7/66.0MB downloaded

[==============================================----] 92.0% 60.7/66.0MB downloaded

[==============================================----] 92.0% 60.7/66.0MB downloaded

[==============================================----] 92.0% 60.7/66.0MB downloaded

[==============================================----] 92.1% 60.7/66.0MB downloaded

[==============================================----] 92.1% 60.7/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.1% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.8/66.0MB downloaded

[==============================================----] 92.2% 60.9/66.0MB downloaded

[==============================================----] 92.2% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.3% 60.9/66.0MB downloaded

[==============================================----] 92.4% 60.9/66.0MB downloaded

[==============================================----] 92.4% 60.9/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.4% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.0/66.0MB downloaded

[==============================================----] 92.5% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.6% 61.1/66.0MB downloaded

[==============================================----] 92.7% 61.1/66.0MB downloaded

[==============================================----] 92.7% 61.1/66.0MB downloaded

[==============================================----] 92.7% 61.1/66.0MB downloaded

[==============================================----] 92.7% 61.2/66.0MB downloaded

[==============================================----] 92.7% 61.2/66.0MB downloaded

[==============================================----] 92.7% 61.2/66.0MB downloaded

[==============================================----] 92.7% 61.2/66.0MB downloaded

[==============================================----] 92.7% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.2/66.0MB downloaded

[==============================================----] 92.8% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 92.9% 61.3/66.0MB downloaded

[==============================================----] 93.0% 61.3/66.0MB downloaded

[==============================================----] 93.0% 61.3/66.0MB downloaded

[==============================================----] 93.0% 61.3/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.0% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.4/66.0MB downloaded

[==============================================----] 93.1% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.2% 61.5/66.0MB downloaded

[==============================================----] 93.3% 61.5/66.0MB downloaded

[==============================================----] 93.3% 61.5/66.0MB downloaded

[==============================================----] 93.3% 61.5/66.0MB downloaded

[==============================================----] 93.3% 61.6/66.0MB downloaded

[==============================================----] 93.3% 61.6/66.0MB downloaded

[==============================================----] 93.3% 61.6/66.0MB downloaded

[==============================================----] 93.3% 61.6/66.0MB downloaded

[==============================================----] 93.3% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.4% 61.6/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.5% 61.7/66.0MB downloaded

[==============================================----] 93.6% 61.7/66.0MB downloaded

[==============================================----] 93.6% 61.7/66.0MB downloaded

[==============================================----] 93.6% 61.7/66.0MB downloaded

[==============================================----] 93.6% 61.8/66.0MB downloaded

[==============================================----] 93.6% 61.8/66.0MB downloaded

[==============================================----] 93.6% 61.8/66.0MB downloaded

[==============================================----] 93.6% 61.8/66.0MB downloaded

[==============================================----] 93.6% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.8/66.0MB downloaded

[==============================================----] 93.7% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.8% 61.9/66.0MB downloaded

[==============================================----] 93.9% 61.9/66.0MB downloaded

[==============================================----] 93.9% 61.9/66.0MB downloaded

[==============================================----] 93.9% 61.9/66.0MB downloaded

[==============================================----] 93.9% 61.9/66.0MB downloaded

[==============================================----] 93.9% 62.0/66.0MB downloaded

[==============================================----] 93.9% 62.0/66.0MB downloaded

[==============================================----] 93.9% 62.0/66.0MB downloaded

[==============================================----] 93.9% 62.0/66.0MB downloaded

[==============================================----] 93.9% 62.0/66.0MB downloaded

[==============================================----] 94.0% 62.0/66.0MB downloaded

[==============================================----] 94.0% 62.0/66.0MB downloaded

[==============================================----] 94.0% 62.0/66.0MB downloaded

[==============================================----] 94.0% 62.0/66.0MB downloaded

[===============================================---] 94.0% 62.0/66.0MB downloaded

[===============================================---] 94.0% 62.0/66.0MB downloaded

[===============================================---] 94.0% 62.0/66.0MB downloaded

[===============================================---] 94.0% 62.0/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.1% 62.1/66.0MB downloaded

[===============================================---] 94.2% 62.1/66.0MB downloaded

[===============================================---] 94.2% 62.1/66.0MB downloaded

[===============================================---] 94.2% 62.1/66.0MB downloaded

[===============================================---] 94.2% 62.1/66.0MB downloaded

[===============================================---] 94.2% 62.2/66.0MB downloaded

[===============================================---] 94.2% 62.2/66.0MB downloaded

[===============================================---] 94.2% 62.2/66.0MB downloaded

[===============================================---] 94.2% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.3% 62.2/66.0MB downloaded

[===============================================---] 94.4% 62.2/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.4% 62.3/66.0MB downloaded

[===============================================---] 94.5% 62.3/66.0MB downloaded

[===============================================---] 94.5% 62.3/66.0MB downloaded

[===============================================---] 94.5% 62.3/66.0MB downloaded

[===============================================---] 94.5% 62.3/66.0MB downloaded

[===============================================---] 94.5% 62.4/66.0MB downloaded

[===============================================---] 94.5% 62.4/66.0MB downloaded

[===============================================---] 94.5% 62.4/66.0MB downloaded

[===============================================---] 94.5% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.6% 62.4/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.7% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.5/66.0MB downloaded

[===============================================---] 94.8% 62.6/66.0MB downloaded

[===============================================---] 94.8% 62.6/66.0MB downloaded

[===============================================---] 94.8% 62.6/66.0MB downloaded

[===============================================---] 94.8% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 94.9% 62.6/66.0MB downloaded

[===============================================---] 95.0% 62.6/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.0% 62.7/66.0MB downloaded

[===============================================---] 95.1% 62.7/66.0MB downloaded

[===============================================---] 95.1% 62.7/66.0MB downloaded

[===============================================---] 95.1% 62.7/66.0MB downloaded

[===============================================---] 95.1% 62.7/66.0MB downloaded

[===============================================---] 95.1% 62.8/66.0MB downloaded

[===============================================---] 95.1% 62.8/66.0MB downloaded

[===============================================---] 95.1% 62.8/66.0MB downloaded

[===============================================---] 95.1% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.2% 62.8/66.0MB downloaded

[===============================================---] 95.3% 62.8/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.3% 62.9/66.0MB downloaded

[===============================================---] 95.4% 62.9/66.0MB downloaded

[===============================================---] 95.4% 62.9/66.0MB downloaded

[===============================================---] 95.4% 62.9/66.0MB downloaded

[===============================================---] 95.4% 62.9/66.0MB downloaded

[===============================================---] 95.4% 62.9/66.0MB downloaded

[===============================================---] 95.4% 63.0/66.0MB downloaded

[===============================================---] 95.4% 63.0/66.0MB downloaded

[===============================================---] 95.4% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.5% 63.0/66.0MB downloaded

[===============================================---] 95.6% 63.0/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.6% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.1/66.0MB downloaded

[===============================================---] 95.7% 63.2/66.0MB downloaded

[===============================================---] 95.7% 63.2/66.0MB downloaded

[===============================================---] 95.7% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.8% 63.2/66.0MB downloaded

[===============================================---] 95.9% 63.2/66.0MB downloaded

[===============================================---] 95.9% 63.2/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 95.9% 63.3/66.0MB downloaded

[===============================================---] 96.0% 63.3/66.0MB downloaded

[===============================================---] 96.0% 63.3/66.0MB downloaded

[===============================================---] 96.0% 63.3/66.0MB downloaded

[===============================================---] 96.0% 63.3/66.0MB downloaded

[================================================--] 96.0% 63.3/66.0MB downloaded

[================================================--] 96.0% 63.4/66.0MB downloaded

[================================================--] 96.0% 63.4/66.0MB downloaded

[================================================--] 96.0% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.1% 63.4/66.0MB downloaded

[================================================--] 96.2% 63.4/66.0MB downloaded

[================================================--] 96.2% 63.4/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.2% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.5/66.0MB downloaded

[================================================--] 96.3% 63.6/66.0MB downloaded

[================================================--] 96.3% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.4% 63.6/66.0MB downloaded

[================================================--] 96.5% 63.6/66.0MB downloaded

[================================================--] 96.5% 63.6/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.5% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.7/66.0MB downloaded

[================================================--] 96.6% 63.8/66.0MB downloaded

[================================================--] 96.6% 63.8/66.0MB downloaded

[================================================--] 96.6% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.7% 63.8/66.0MB downloaded

[================================================--] 96.8% 63.8/66.0MB downloaded

[================================================--] 96.8% 63.8/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.8% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 63.9/66.0MB downloaded

[================================================--] 96.9% 64.0/66.0MB downloaded

[================================================--] 96.9% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.0% 64.0/66.0MB downloaded

[================================================--] 97.1% 64.0/66.0MB downloaded

[================================================--] 97.1% 64.0/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.1% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.1/66.0MB downloaded

[================================================--] 97.2% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.3% 64.2/66.0MB downloaded

[================================================--] 97.4% 64.2/66.0MB downloaded

[================================================--] 97.4% 64.2/66.0MB downloaded

[================================================--] 97.4% 64.2/66.0MB downloaded

[================================================--] 97.4% 64.3/66.0MB downloaded

[================================================--] 97.4% 64.3/66.0MB downloaded

[================================================--] 97.4% 64.3/66.0MB downloaded

[================================================--] 97.4% 64.3/66.0MB downloaded

[================================================--] 97.4% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.3/66.0MB downloaded

[================================================--] 97.5% 64.4/66.0MB downloaded

[================================================--] 97.5% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.6% 64.4/66.0MB downloaded

[================================================--] 97.7% 64.4/66.0MB downloaded

[================================================--] 97.7% 64.4/66.0MB downloaded

[================================================--] 97.7% 64.4/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.7% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.5/66.0MB downloaded

[================================================--] 97.8% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 97.9% 64.6/66.0MB downloaded

[================================================--] 98.0% 64.6/66.0MB downloaded

[================================================--] 98.0% 64.6/66.0MB downloaded

[================================================--] 98.0% 64.6/66.0MB downloaded

[================================================--] 98.0% 64.7/66.0MB downloaded

[=================================================-] 98.0% 64.7/66.0MB downloaded

[=================================================-] 98.0% 64.7/66.0MB downloaded

[=================================================-] 98.0% 64.7/66.0MB downloaded

[=================================================-] 98.0% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.7/66.0MB downloaded

[=================================================-] 98.1% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.2% 64.8/66.0MB downloaded

[=================================================-] 98.3% 64.8/66.0MB downloaded

[=================================================-] 98.3% 64.8/66.0MB downloaded

[=================================================-] 98.3% 64.8/66.0MB downloaded

[=================================================-] 98.3% 64.9/66.0MB downloaded

[=================================================-] 98.3% 64.9/66.0MB downloaded

[=================================================-] 98.3% 64.9/66.0MB downloaded

[=================================================-] 98.3% 64.9/66.0MB downloaded

[=================================================-] 98.3% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 64.9/66.0MB downloaded

[=================================================-] 98.4% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.5% 65.0/66.0MB downloaded

[=================================================-] 98.6% 65.0/66.0MB downloaded

[=================================================-] 98.6% 65.0/66.0MB downloaded

[=================================================-] 98.6% 65.0/66.0MB downloaded

[=================================================-] 98.6% 65.0/66.0MB downloaded

[=================================================-] 98.6% 65.1/66.0MB downloaded

[=================================================-] 98.6% 65.1/66.0MB downloaded

[=================================================-] 98.6% 65.1/66.0MB downloaded

[=================================================-] 98.6% 65.1/66.0MB downloaded

[=================================================-] 98.6% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.7% 65.1/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.8% 65.2/66.0MB downloaded

[=================================================-] 98.9% 65.2/66.0MB downloaded

[=================================================-] 98.9% 65.2/66.0MB downloaded

[=================================================-] 98.9% 65.2/66.0MB downloaded

[=================================================-] 98.9% 65.2/66.0MB downloaded

[=================================================-] 98.9% 65.3/66.0MB downloaded

[=================================================-] 98.9% 65.3/66.0MB downloaded

[=================================================-] 98.9% 65.3/66.0MB downloaded

[=================================================-] 98.9% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.0% 65.3/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.1% 65.4/66.0MB downloaded

[=================================================-] 99.2% 65.4/66.0MB downloaded

[=================================================-] 99.2% 65.4/66.0MB downloaded

[=================================================-] 99.2% 65.4/66.0MB downloaded

[=================================================-] 99.2% 65.4/66.0MB downloaded

[=================================================-] 99.2% 65.5/66.0MB downloaded

[=================================================-] 99.2% 65.5/66.0MB downloaded

[=================================================-] 99.2% 65.5/66.0MB downloaded

[=================================================-] 99.2% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.3% 65.5/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.4% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.6/66.0MB downloaded

[=================================================-] 99.5% 65.7/66.0MB downloaded

[=================================================-] 99.5% 65.7/66.0MB downloaded

[=================================================-] 99.5% 65.7/66.0MB downloaded

[=================================================-] 99.5% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.6% 65.7/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.7% 65.8/66.0MB downloaded

[=================================================-] 99.8% 65.8/66.0MB downloaded

[=================================================-] 99.8% 65.8/66.0MB downloaded

[=================================================-] 99.8% 65.8/66.0MB downloaded

[=================================================-] 99.8% 65.8/66.0MB downloaded

[=================================================-] 99.8% 65.9/66.0MB downloaded

[=================================================-] 99.8% 65.9/66.0MB downloaded

[=================================================-] 99.8% 65.9/66.0MB downloaded

[=================================================-] 99.8% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 99.9% 65.9/66.0MB downloaded

[=================================================-] 100.0% 65.9/66.0MB downloaded

[=================================================-] 100.0% 66.0/66.0MB downloaded

[=================================================-] 100.0% 66.0/66.0MB downloaded

[=================================================-] 100.0% 66.0/66.0MB downloaded

[=================================================-] 100.0% 66.0/66.0MB downloaded

[==================================================] 100.0% 66.0/66.0MB downloaded

Embedding used: pre-trained GloVe 50d
Average word-vector sentence matrix shape: (12, 50)

        0      1      2      3      4      5      6      7      8      9
S1 -0.829  0.020 -0.509  0.691  0.114 -0.666 -0.734  0.624 -0.529 -0.309
S2 -0.722  0.088 -0.882  0.871  0.001 -0.335 -0.342  0.929  0.048 -0.427
S3 -0.280  0.017  0.151  0.110 -0.172 -0.221 -0.371  0.721 -0.328  0.099

In [25]:
S_tfidf = cosine_similarity(T4)
S_avg = cosine_similarity(A4)
pairs4 = [(0, 1), (0, 3), (4, 5), (4, 6), (8, 9), (8, 10), (0, 4), (7, 11)]
rows = [(ids4[a], ids4[b], round(S_tfidf[a, b], 3), round(S_avg[a, b], 3)) for a, b in pairs4]
pd.DataFrame(rows, columns=["Sent A", "Sent B", "Cos (TF-IDF)", "Cos (Avg W2V)"])

  Sent A Sent B  Cos (TF-IDF)  Cos (Avg W2V)
0     S1     S2         0.342          0.947
1     S1     S4         0.342          0.937
2     S5     S6         0.277          0.854
3     S5     S7         0.277          0.909
4     S9    S10         0.147          0.884
5     S9    S11         0.120          0.833
6     S1     S5         0.000          0.355
7     S8    S12         0.000          0.450

In [26]:
km = KMeans(n_clusters=3, n_init=10, random_state=42).fit(T4.toarray())
res = pd.DataFrame({"Sentence": sent4, "True topic": topic4, "Cluster": km.labels_}, index=ids4)
res.sort_values("Cluster")

                                             Sentence True topic  Cluster
S8         Programmers write code for learning models    ai_tech        0
S7               Deep learning models need large data    ai_tech        0
S6   Machine learning models learn from training data    ai_tech        0
S5     Neural networks learn patterns from large data    ai_tech        0
S12     Fresh vegetables and fruits make healthy food       food        1
S11            The restaurant serves fresh spicy food       food        1
S10             The chef baked a sweet chocolate cake       food        1
S9      The chef cooked fresh pasta with tomato sauce       food        1
S1          The football team won the match yesterday     sports        2
S2               The cricket team won the final match     sports        2
S3                Players train hard before the match     sports        2
S4         The coach praised the team after the match     sports        2

In [27]:
doc_vecs = {}
for topic in ["sports", "ai_tech", "food"]:
    ix = [i for i, t in enumerate(topic4) if t == topic]
    doc_vecs[topic] = {"tfidf_mean": T4.toarray()[ix].mean(0), "w2v_mean": A4[ix].mean(0)}
print("Doc vector dims -> TF-IDF:", doc_vecs["sports"]["tfidf_mean"].shape, "| Word2Vec:", doc_vecs["sports"]["w2v_mean"].shape)
D = np.vstack([doc_vecs[t]["tfidf_mean"] for t in doc_vecs])
pd.DataFrame(cosine_similarity(D), index=list(doc_vecs), columns=list(doc_vecs)).round(3)

Doc vector dims -> TF-IDF: (44,) | Word2Vec: (50,)

         sports  ai_tech  food
sports      1.0      0.0   0.0
ai_tech     0.0      1.0   0.0
food        0.0      0.0   1.0

In [28]:
comp = pd.DataFrame({
    "Level": ["Word (co-occurrence, Q3)", "Word (Word2Vec)", "Sentence (TF-IDF)", "Sentence (Avg W2V)", "Document (mean of sentences)"],
    "Dimension": [len(vocab3), w2v.vector_size, T4.shape[1], A4.shape[1], f"{T4.shape[1]} or {A4.shape[1]}"],
    "Type": ["sparse, count based", "dense, learned", "sparse, lexical", "dense, semantic", "aggregated, dense or sparse"],
    "Captures word order": ["no", "no", "no", "no", "no"],
})
comp

                          Level Dimension                         Type Captures word order
0      Word (co-occurrence, Q3)        41          sparse, count based                  no
1               Word (Word2Vec)        30               dense, learned                  no
2             Sentence (TF-IDF)        44              sparse, lexical                  no
3            Sentence (Avg W2V)        50              dense, semantic                  no
4  Document (mean of sentences)  44 or 50  aggregated, dense or sparse                  no

**Challenges of fixed-length vectors for sentences and documents**

- **Word order lost:** averaging or bag-of-words treats "dog bites man" and "man bites dog" alike.
- **Information bottleneck:** long texts with many ideas get compressed into one vector, diluting details.
- **Averaging dilution:** frequent or unimportant words shift the mean; a single key word can be washed out.
- **Polysemy and context:** one vector per word cannot separate meanings (bank: river vs money).
- **Negation and compositionality:** "good" and "not good" get nearly the same vector.
- **Vocabulary limits:** out-of-vocabulary words are ignored; sparse TF-IDF vectors miss synonyms.
- **Variable length:** a document with 10 or 10,000 words maps to the same size, so scale and structure are lost.
- Better options: contextual encoders such as Sentence-BERT, or doc2vec.